### ISSUE TITLE
Public JS in ERPNext and Frappe are not updating on subsequence deployment.

### ISSUE THREAD

**Issue by AuntMaungGreenPhyto** [frappe/frappe_docker#1020]
Someone can help as I cannot get updated JS(Modified JS) on subsequence deployment.  
The following is yaml file. 

services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext-worker:gp.v14.3.1
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      read_only: true
      volume: {}
  configurator:
    command:
    - configure.py
    depends_on:
      redis:
        condition: service_started
    environment:
      DB_HOST: mariadb-database
      DB_PORT: "3306"
      REDIS_CACHE: redis:6379/0
      REDIS_QUEUE: redis:6379/1
      REDIS_SOCKETIO: redis:6379/2
      SOCKETIO_PORT: "9000"
    image: frappe/erpnext-worker:gp.v14.3.1
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      read_only: true
      volume: {}
  frontend:
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: $$host
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: frappe/erpnext-nginx:gp.v14.3.1
    labels:
      traefik.docker.network: traefik-public
      traefik.enable: "true"
      traefik.http.routers.erpnext-greenphyto-http.entrypoints: http
      traefik.http.routers.erpnext-greenphyto-http.middlewares: https-redirect
      traefik.http.routers.erpnext-greenphyto-http.rule: Host(`erp-dev.greenphyto.com`,`two.example.com`)
      traefik.http.routers.erpnext-greenphyto-http.service: erpnext-greenphyto
      traefik.http.routers.erpnext-greenphyto-https.entrypoints: https
      traefik.http.routers.erpnext-greenphyto-https.rule: Host(`erp-dev.greenphyto.com`,`two.example.com`)
      traefik.http.routers.erpnext-greenphyto-https.service: erpnext-greenphyto
      traefik.http.routers.erpnext-greenphyto-https.tls: "true"
      traefik.http.routers.erpnext-greenphyto-https.tls.certresolver: le
      traefik.http.services.erpnext-greenphyto.loadbalancer.server.port: "8080"
    networks:
      bench-network: null
      traefik-public: null
    volumes:
    - type: volume
      source: assets
      target: /usr/share/nginx/html/assets
      volume: {}
    - type: volume
      source: sites
      target: /usr/share/nginx/html/sites
      volume: {}
  queue-default:
    command:
    - bench
    - worker
    - --queue
    - default
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext-worker:gp.v14.3.1
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      read_only: true
      volume: {}
  queue-long:
    command:
    - bench
    - worker
    - --queue
    - long
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext-worker:gp.v14.3.1
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      read_only: true
      volume: {}
  queue-short:
    command:
    - bench
    - worker
    - --queue
    - short
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext-worker:gp.v14.3.1
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      read_only: true
      volume: {}
  redis:
    image: redis:6.2-alpine
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: redis-data
      target: /data
      volume: {}
  scheduler:
    command:
    - bench
    - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext-worker:gp.v14.3.1
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
    - type: volume
      source: assets
      target: /home/frappe/frappe-bench/sites/assets
      read_only: true
      volume: {}
  websocket:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/frappe-socketio:gp.v14.12.0
    networks:
      bench-network: null
      mariadb-network: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
networks:
  bench-network:
    name: erpnext-greenphyto
  mariadb-network:
    name: mariadb-network
    external: true
  traefik-public:
    name: traefik-public
    external: true
volumes:
  assets:
    name: erpnext-greenphyto_assets
  redis-data:
    name: erpnext-greenphyto_redis-data
  sites:
    name: erpnext-greenphyto_sites
x-backend-defaults:
  depends_on:
    configurator:
      condition: service_completed_successfully
  image: frappe/frappe-worker:gp.v14.12.0
  volumes:
  - sites:/home/frappe/frappe-bench/sites
  - assets:/home/frappe/frappe-bench/sites/assets:ro
x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
x-erpnext-backend-image:
  image: frappe/erpnext-worker:gp.v14.3.1

**Comment by revant** [comment]
Please format the code before posting. It helps differentiate text blocks.

Add following service with appropriate `VERSION`, volumes and networks,

To update schema:

```yaml
  migration:
    image: frappe/erpnext-worker:${VERSION}
    deploy:
      restart_policy:
        condition: none
    entrypoint: ["bash", "-c"]
    command:
      - |
        for SITE in $$(/home/frappe/frappe-bench/env/bin/python -c "import frappe;print(' '.join(frappe.utils.get_sites()))")
        do
          bench --site $$SITE set-config -p maintenance_mode 1
          bench --site $$SITE set-config -p pause_scheduler 1
          bench --site $$SITE migrate
          bench --site $$SITE set-config -p maintenance_mode 0
          bench --site $$SITE set-config -p pause_scheduler 0
        done
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets
```

To populate assets:

```yaml
  populate-assets:
    image: frappe/erpnext-nginx:${VERSION}
    deploy:
      restart_policy:
        condition: none
    entrypoint: ["sh", "-c"]
    command:
      - >
        cp -fR /usr/share/nginx/html/assets /data;
        touch /data/sites/.build;
    volumes:
      - assets:/data/assets:rw
      - sites:/data/sites:rw
```

This can be done manually.

Reference in docs:
- populate assets: https://github.com/frappe/frappe_docker/blob/main/docs/setup-options.md#updating-images
- update schema: https://github.com/frappe/frappe_docker/blob/main/docs/site-operations.md#migrate-site
