### ISSUE TITLE
How to add domain and SSL Certificate

### ISSUE THREAD

**Issue by iamshouvikmitra** [frappe/frappe_docker#1055]
I have freshly installed frappe using the easy install script. Here's what my docker containers look like 
![Screenshot from 2023-01-23 00-30-11](https://user-images.githubusercontent.com/24479402/213934631-f3588d04-0bbf-4ee7-a414-25e7d0a45183.png)

The VM has a static IP attached to it and I have updated my dns to point erp.mycompany.com to that static ip. During easy install i did provide an email using --email flag, which I though was supposed to install a let's encrypt certificate. Anyways, at the moment, if I visit erp.mycompany.com there is an SSL error with an invalid certificate as shown below. 
![Screenshot from 2023-01-23 00-33-21](https://user-images.githubusercontent.com/24479402/213934809-3c288d3c-a384-4a32-b447-366e9f8dc5cb.png)

Moreover, I was able to setup outbound emails and the URLs in the templates for password confirmation point to http://erp.mycompany.com:8000 instead of http://erp.mycompany.com  

Not sure if I have messed anything during the installation and also ironic that during the entire setup I was never asked of any domains. I am new the entire frappe ecosystem and trying to get started with the same. All I am aware at the moment is that there is a cli called bench which I can run using `docker compose exec backend bench`

Thanks to anyone who can help guide me set it up properly.

**Comment by iamshouvikmitra** [comment]
knock knock!

**Comment by revant** [comment]
Anything in traefik logs? It should be trying to get letsencrypt certificate.

**Comment by FabioSBE** [comment]
I have the same issue.

**Comment by iamshouvikmitra** [comment]
Finally figured it out, 

Post installation to enable SSL, ensure that your docker-compose.yml file for your site has the following line 
```
traefik.http.routers.frontend-http.tls.domains[0].main: "yourdomain.com"  
```

if not add it under the labels: inside frontend service, thus your frontend service should look like 
```
...
  frontend:
    command:
    - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: UMT
      PROXY_READ_TIMOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: frappe/erpnext:v14.12.1
    labels:
      traefik.enable: "true"
      traefik.http.routers.frontend-http.entrypoints: websecure
      traefik.http.routers.frontend-http.rule: HostRegexp(`{any:.+}`)
      traefik.http.routers.frontend-http.tls.certresolver: main-resolver
      traefik.http.routers.frontend-http.tls.domains[0].main: "yourdomain.com"
      traefik.http.services.frontend.loadbalancer.server.port: "8080"
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}

...
```


Once added, simply run `docker compose down` > `docker compose build --no-cache`  > `docker compose up -d`

Now SSL should work fine.

Now, to ensure that emails go using correct port, follow the instructions below
1. `docker compose exec frontend bench setup add-domain yourdomain.com`
2. `docker compose exec frontend bench setup nginx`
3. `docker compose exec frontend bench set-nginx-port yoursite 80`
4. `docker compose exec -it frontend bash`
5. Once you are inside the frontend container, run `vi sites/common_site_config.json`
6. Change the `webserver_port` key from 8000 to 443 and save the file 

Now emails should have :443 as the port and since you have ssl enabled the link in the email would not be broken

Let me know if this works for you @FabioSBE 


Note: 
Change `yourdomain.com` with your actual domain and `yoursite` with actual site installation name.
