### ISSUE TITLE
Cannot start container - Invalid interpolation format

### ISSUE THREAD

**Issue by nikkilocke** [frappe/frappe_docker#1069]
## Description of the issue
I can't seem to start the containers with docker-compose. All I am trying to do is to run erpnext in a docker container.

## Context information (for bug reports)
docker-compose version 1.17.1, build unknown
Docker version 20.10.12, build 20.10.12-0ubuntu2~18.04.1

## Steps to reproduce the issue

I cloned the repo. I copied a .env file from example.env.  

I tried to start the container with:

`sudo docker-compose -f compose.yaml -f overrides/compose.redis.yaml -f overrides/compose.mariadb.yaml up -d`

### Observed result
```
ERROR: Invalid interpolation format for "queue-long" option in service "services": "frappe/erpnext:${ERPNEXT_VERSION:?No ERPNext version set}"
nikki@xr:~/frappe_docker$ ./compose up -d
ERROR: Invalid interpolation format for "frontend" option in service "services": "${UPSTREAM_REAL_IP_RECURSIVE:-off}"
nikki@xr:~/frappe_docker$ ./compose up -d
ERROR: Invalid interpolation format for "frontend" option in service "services": "${UPSTREAM_REAL_IP_RECURSIVE:off}"
nikki@xr:~/frappe_docker$ ./compose up -d
ERROR: Invalid interpolation format for "queue-long" option in service "services": "frappe/erpnext:${ERPNEXT_VERSION:?No ERPNext version set}"
```
### Expected result
Container starts

**Comment by revant** [comment]
It worked for me with docker compose v2

<details>

<summary>docker compose</summary>

```
❯ cd /tmp
❯ git clone https://github.com/frappe/frappe_docker.git
Cloning into 'frappe_docker'...
cd frremote: Enumerating objects: 7902, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (36/36), done.
Receiving objects:  67% (5295/7902), 2.60 MiB | 1.70 MiB/sB/s 
remote: Total 7902 (delta 18), reused 33 (delta 9), pack-reused 7854
Receiving objects: 100% (7902/7902), 9.49 MiB | 2.21 MiB/s, done.
Resolving deltas: 100% (3371/3371), done.
❯ cd frappe_docker
❯ cp example.env .env
❯ docker compose -f compose.yaml -f overrides/compose.redis.yaml -f overrides/compose.mariadb.yaml config
name: frappe_docker
services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.15.0
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  configurator:
    command:
    - |
      bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
      redis-socketio:
        condition: service_started
    entrypoint:
    - bash
    - -c
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
      SOCKETIO_PORT: "9000"
    image: frappe/erpnext:v14.15.0
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  db:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-character-set-client-handshake
    - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: "123"
    healthcheck:
      test:
      - CMD-SHELL
      - mysqladmin ping -h localhost --password=123
      interval: 1s
      retries: 15
    image: mariadb:10.6
    networks:
      default: null
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
      volume: {}
  frontend:
    command:
    - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: frappe/erpnext:v14.15.0
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-default:
    command:
    - bench
    - worker
    - --queue
    - default
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.15.0
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-long:
    command:
    - bench
    - worker
    - --queue
    - long
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.15.0
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-short:
    command:
    - bench
    - worker
    - --queue
    - short
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.15.0
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  redis-cache:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: redis-cache-data
      target: /data
      volume: {}
  redis-queue:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: redis-queue-data
      target: /data
      volume: {}
  redis-socketio:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: redis-socketio-data
      target: /data
      volume: {}
  scheduler:
    command:
    - bench
    - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.15.0
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  websocket:
    command:
    - node
    - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v14.15.0
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
networks:
  default:
    name: frappe_docker_default
volumes:
  db-data:
    name: frappe_docker_db-data
  redis-cache-data:
    name: frappe_docker_redis-cache-data
  redis-queue-data:
    name: frappe_docker_redis-queue-data
  redis-socketio-data:
    name: frappe_docker_redis-socketio-data
  sites:
    name: frappe_docker_sites
x-backend-defaults:
  depends_on:
    configurator:
      condition: service_completed_successfully
  image: frappe/erpnext:v14.15.0
  volumes:
  - sites:/home/frappe/frappe-bench/sites
x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
❯ docker compose -f compose.yaml -f overrides/compose.redis.yaml -f overrides/compose.mariadb.yaml up -d
[+] Running 18/18
 ⠿ Network frappe_docker_default               Created                                                                                                                                     0.1s
 ⠿ Volume "frappe_docker_db-data"              Created                                                                                                                                     0.0s
 ⠿ Volume "frappe_docker_redis-cache-data"     Created                                                                                                                                     0.0s
 ⠿ Volume "frappe_docker_redis-queue-data"     Created                                                                                                                                     0.0s
 ⠿ Volume "frappe_docker_redis-socketio-data"  Created                                                                                                                                     0.0s
 ⠿ Volume "frappe_docker_sites"                Created                                                                                                                                     0.0s
 ⠿ Container frappe_docker-db-1                Healthy                                                                                                                                     4.9s
 ⠿ Container frappe_docker-redis-cache-1       Started                                                                                                                                     1.3s
 ⠿ Container frappe_docker-redis-queue-1       Started                                                                                                                                     1.4s
 ⠿ Container frappe_docker-redis-socketio-1    Started                                                                                                                                     1.4s
 ⠿ Container frappe_docker-configurator-1      Exited                                                                                                                                     14.2s
 ⠿ Container frappe_docker-scheduler-1         Started                                                                                                                                    14.8s
 ⠿ Container frappe_docker-backend-1           Started                                                                                                                                    15.1s
 ⠿ Container frappe_docker-queue-long-1        Started                                                                                                                                    15.3s
 ⠿ Container frappe_docker-queue-short-1       Started                                                                                                                                    14.9s
 ⠿ Container frappe_docker-queue-default-1     Started                                                                                                                                    15.3s
 ⠿ Container frappe_docker-websocket-1         Started                                                                                                                                    15.1s
 ⠿ Container frappe_docker-frontend-1          Started                                                                                                                                    15.7s

❯ docker ps
CONTAINER ID   IMAGE                     COMMAND                  CREATED              STATUS                        PORTS      NAMES
2ef20bf189d1   frappe/erpnext:v14.15.0   "nginx-entrypoint.sh"    About a minute ago   Up About a minute                        frappe_docker-frontend-1
11cb322f3c6b   frappe/erpnext:v14.15.0   "/home/frappe/frappe…"   About a minute ago   Up About a minute                        frappe_docker-backend-1
85f796adcead   frappe/erpnext:v14.15.0   "bench worker --queu…"   About a minute ago   Up About a minute                        frappe_docker-queue-short-1
50e9f3fbffef   frappe/erpnext:v14.15.0   "node /home/frappe/f…"   About a minute ago   Up About a minute                        frappe_docker-websocket-1
4675819e7e1e   frappe/erpnext:v14.15.0   "bench worker --queu…"   About a minute ago   Up About a minute                        frappe_docker-queue-default-1
01bd4595529c   frappe/erpnext:v14.15.0   "bench schedule"         About a minute ago   Up About a minute                        frappe_docker-scheduler-1
2e9923c1fc0f   frappe/erpnext:v14.15.0   "bench worker --queu…"   About a minute ago   Up About a minute                        frappe_docker-queue-long-1
14923416d3f8   redis:6.2-alpine          "docker-entrypoint.s…"   About a minute ago   Up About a minute             6379/tcp   frappe_docker-redis-cache-1
0f8cceb509a6   mariadb:10.6              "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   3306/tcp   frappe_docker-db-1
2c5a9af19438   redis:6.2-alpine          "docker-entrypoint.s…"   About a minute ago   Up About a minute             6379/tcp   frappe_docker-redis-socketio-1
b4c895697c6c   redis:6.2-alpine          "docker-entrypoint.s…"   About a minute ago   Up About a minute             6379/tcp   frappe_docker-redis-queue-1

```

</details>

I can help as I can't reproduce issue on my machine with docker compose v2. May be someone else may help.
