### ISSUE TITLE
retriving the original IP address

### ISSUE THREAD

**Issue by sdfateh** [frappe/frappe_docker#1074]
How to retrive the original IP address for the requestes ?

I changed the value for the variables:
        real_ip_recursive on;
        set_real_ip_from 0.0.0.0/0;
        real_ip_header X-Forwarded-For;

If I connect directly to the server , it works !

But If I use Nginx reverse proxy I always have the reverse proxy IP

Any Advice?

**Comment by sdfateh** [comment]
@revant your input is thankful

**Comment by revant** [comment]
I haven't used it. I guess @Xaroth can help as the owner of the contribution https://github.com/frappe/frappe_docker/pull/419

**Comment by revant** [comment]
@sdfateh 
what do you get in `X-Forwarded-For` header?

**Comment by sdfateh** [comment]
Reverse Proxy IP address

**Comment by revant** [comment]
https://nginx.org/en/docs/http/ngx_http_upstream_module.html

we'll have to figure out from nginx docs. 
you can try to fix it with config override, if it works we'll change the template

**Comment by sdfateh** [comment]
I'm currently implementing a workaround to maintain business continuity.
I will work on a radical solution to the issue and share it

**Comment by flortsch** [comment]
What is your nginx reverse proxy config?
In your config, you have to set directives such as:

```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by revant** [comment]
> What is your nginx reverse proxy config?

https://github.com/frappe/frappe_docker/blob/main/resources/nginx-template.conf

this is a template, environment variables are substituted and final config is generated from it.

**Comment by sdfateh** [comment]
@flortsch 
        location @webserver {


                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Frappe-Site-Name $host;
                proxy_set_header X-Use-X-Accel-Redirect True;
                proxy_read_timeout 600;
                proxy_redirect off;

                proxy_pass  https://webserver;
        }

**Comment by flortsch** [comment]
Yes, this is the config of the ERPNext Nginx instance and for me, it's working as expected. I am running an Nginx reverse proxy myself on the host (with the headers I posted above), which proxies all requests to the ERPNext Nginx instance running in the Docker container (with env vars `UPSTREAM_REAL_IP_ADDRESS=172.20.0.1` and `UPSTREAM_REAL_IP_HEADER=X-Forwarded-For` in my case, you have to change them accordingly). If you are running ERPNext Nginx directly without a reverse proxy in front of it, there is no need for passing any of these reverse proxy directives or env vars.

**Comment by flortsch** [comment]
My reverse proxy config:

```
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

upstream erpnext {
  server 172.20.0.1:8080;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name erp.mydomain.com;

  ssl_certificate /etc/letsencrypt/live/erp.mydomain.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/erp.mydomain.com/privkey.pem;

  location / {
    include proxy_params; #proxy_params is a file in /etc/nginx with the proxy_set_header directives posted before
    proxy_read_timeout 300s;
    proxy_pass http://erpnext;
  }

  location /socket.io {
    include proxy_params; #proxy_params is a file in /etc/nginx with the proxy_set_header directives posted before
    proxy_http_version 1.1;
    proxy_read_timeout 36000s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_pass http://erpnext;
  }
}

server {
  listen 80;
  listen [::]:80;
  server_name erp.mydomain.com;

  return 301 https://erp.mydomain.com$request_uri;
}

```

My Ansible task for creating the ERPNext Nginx container (you can see the env vars):

```
- name: Create erpnext-frontend container
  community.docker.docker_container:
    name: erpnext-frontend
    image: 'frappe/erpnext:{{ erpnext_version }}'
    command: nginx-entrypoint.sh
    restart_policy: always
    networks:
      - name: erpnext-network
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
    ports:
      - 172.20.0.1:8080:8080
    env:
      BACKEND: erpnext-backend:8000
      SOCKETIO: erpnext-socketio:9000
      FRAPPE_SITE_NAME_HEADER: $host
      UPSTREAM_REAL_IP_ADDRESS: 172.20.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
```
