### ISSUE TITLE
Is it possible to make ERPNext run after reboot

### ISSUE THREAD

**Issue by jrGabrillo** [frappe/frappe_docker#1083]
I tried updating the yml files by adding `restart: unless-stopped`. The Traefik and MariaDB work well but the ERPNext containers keep restarting after reboot. 

How to make ERPNext run without issue after reboot?

Here's a screenshot of running docker containers after reboot. Everything works before reboot. 
![Screenshot 2023-02-23 at 11 50 45 PM](https://user-images.githubusercontent.com/19164950/220959226-aee6a30b-9c34-4251-8a8d-254d3abfb740.png)

Here is my frappe_docker/docs/compose/compose.multi-bench.yaml
```
services:
  frontend:
    restart: unless-stopped
    networks:
      - traefik-public
      - bench-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.${ROUTER?ROUTER not set}.loadbalancer.server.port=8080
      - traefik.http.routers.${ROUTER}-http.service=${ROUTER}
      - traefik.http.routers.${ROUTER}-http.entrypoints=http
      - traefik.http.routers.${ROUTER}-http.rule=Host(${SITES?SITES not set})
  configurator:
    networks:
      - bench-network
      - mariadb-network
  backend:
    restart: unless-stopped
    networks:
      - mariadb-network
      - bench-network
  websocket:
    restart: unless-stopped
    networks:
      - bench-network
      - mariadb-network
  scheduler:
    restart: unless-stopped
    networks:
      - bench-network
      - mariadb-network
  queue-default:
    restart: unless-stopped
    networks:
      - bench-network
      - mariadb-network
  queue-short:
    restart: unless-stopped
    networks:
      - bench-network
      - mariadb-network
  queue-long:
    restart: unless-stopped
    networks:
      - bench-network
      - mariadb-network
  redis:
    restart: unless-stopped
    networks:
      - bench-network
      - mariadb-network

networks:
  traefik-public:
    external: true
  mariadb-network:
    external: true
  bench-network:
    name: ${ROUTER}
    external: false

```
