### ISSUE TITLE
redis-server not found - custom docker image

### ISSUE THREAD

**Issue by vpanchal-code** [frappe/frappe_docker#1105]
## Description of the issue
When I try to setup procfile and bench start, it keeps giving me an error that `redis-server: not found`. I checked and the redis containers are running.

I have generated a custom docker image and the compose file generate and started. It shows that the my redis server is running:
```
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
f135f7248f57   docker.simplementix.com/erpnext:23.03.16   "nginx-entrypoint.sh"    19 minutes ago   Up 18 minutes             0.0.0.0:6880->8080/tcp, :::6880->8080/tcp   simplementix-frontend-1
96531c63284b   docker.simplementix.com/erpnext:23.03.16   "bench worker --queu…"   19 minutes ago   Up 19 minutes                                                         simplementix-queue-default-1
b8748b892678   docker.simplementix.com/erpnext:23.03.16   "bench worker --queu…"   19 minutes ago   Up 18 minutes                                                         simplementix-queue-long-1
7e8c830e65b5   docker.simplementix.com/erpnext:23.03.16   "bench worker --queu…"   19 minutes ago   Up 18 minutes                                                         simplementix-queue-short-1
0752736d0fae   docker.simplementix.com/erpnext:23.03.16   "node /home/frappe/f…"   19 minutes ago   Up 18 minutes                                                         simplementix-websocket-1
61b7ef636c30   docker.simplementix.com/erpnext:23.03.16   "/home/frappe/frappe…"   19 minutes ago   Up 18 minutes                                                         simplementix-backend-1
ca8c13c9e525   docker.simplementix.com/erpnext:23.03.16   "bench schedule"         19 minutes ago   Up 19 minutes                                                         simplementix-scheduler-1
86ad1c5a5b05   mariadb:10.6                               "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes (healthy)   3306/tcp                                    simplementix-db-1
796c6910ae09   redis:6.2-alpine                           "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes             6379/tcp                                    simplementix-redis-queue-1
931c5c67a51c   redis:6.2-alpine                           "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes             6379/tcp                                    simplementix-redis-cache-1
f9a13e59291d   redis:6.2-alpine                           "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes             6379/tcp                                    simplementix-redis-socketio-1

```

## Context information (for bug reports)
Running on arm64 device running ubuntu 22.04 server
docker version: 23.0.1
docker compose version: 2.16.0

Docker Compose File:
```
name: frappe_docker
services:
  backend:
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: docker.simplementix.com/erpnext:23.03.16
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  configurator:
    command:
    - |
      ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
      redis-socketio:
        condition: service_started
    entrypoint:
    - bash
    - -c
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
      SOCKETIO_PORT: "9000"
    image: docker.simplementix.com/erpnext:23.03.16
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  db:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-character-set-client-handshake
    - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: MYPASSWORD
    healthcheck:
      test:
      - CMD-SHELL
      - mysqladmin ping -h localhost --password=MYPASSWORD
      interval: 1s
      retries: 15
    image: mariadb:10.6
    networks:
      default: null
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
      volume: {}
  frontend:
    command:
    - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: docker.simplementix.com/erpnext:23.03.16
    networks:
      default: null
    ports:
     - 6880:8080
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-default:
    command:
    - bench
    - worker
    - --queue
    - default
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: docker.simplementix.com/erpnext:23.03.16
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-long:
    command:
    - bench
    - worker
    - --queue
    - long
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: docker.simplementix.com/erpnext:23.03.16
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-short:
    command:
    - bench
    - worker
    - --queue
    - short
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: docker.simplementix.com/erpnext:23.03.16
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  redis-cache:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: redis-cache-data
      target: /data
      volume: {}
  redis-queue:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: redis-queue-data
      target: /data
      volume: {}
  redis-socketio:
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: redis-socketio-data
      target: /data
      volume: {}
  scheduler:
    command:
    - bench
    - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: docker.simplementix.com/erpnext:23.03.16
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  websocket:
    command:
    - node
    - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: docker.simplementix.com/erpnext:23.03.16
    networks:
      default: null
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
networks:
  default:
    name: frappe_docker_default
volumes:
  db-data:
    name: frappe_docker_db-data
    external: true
  redis-cache-data:
    name: frappe_docker_redis-cache-data
    external: true
  redis-queue-data:
    name: frappe_docker_redis-queue-data
    external: true
  redis-socketio-data:
    name: frappe_docker_redis-socketio-data
    external: true
  sites:
    name: frappe_docker_sites
    external: true
x-backend-defaults:
  depends_on:
    configurator:
      condition: service_completed_successfully
  image: docker.simplementix.com/erpnext:23.03.16
  volumes:
  - sites:/home/frappe/frappe-bench/sites
x-customizable-image:
  image: docker.simplementix.com/erpnext:23.03.16
x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
```

My env file:
```
# Reference: https://github.com/frappe/frappe_docker/blob/main/docs/images-and-compose-files.md

ERPNEXT_VERSION=v14.18.3

DB_PASSWORD=MYPASSWORD

# List of sites for letsencrypt certificates quoted with backtick (`) and separated by comma (,)
# More https://doc.traefik.io/traefik/routing/routers/#rule
# About acme https://doc.traefik.io/traefik/https/acme/#domain-definition
SITES=`erp.simplementix.com`
```
commands used to setup site:
```
docker exec simplementix-backend-1 bench new-site erp.simplementix.com --no-mariadb-socket --mariadb-root-password MYPASSWORD --admin-password MYADMINPASSWORD --install-app payments
docker exec simplementix-backend-1 bench --site erp.simplementix.com install-app erpnext expense_request hrms wiki
```
## Steps to reproduce the issue

1.  start docker compose file: `docker compose --project-name simplementix -f erpnext/docker-compose.yml up -d`
2. create procfile: `docker exec simplementix-backend-1 bench setup procfile`
3. start bench: `docker exec simplementix-backend-1 bench start`

### Observed result
```
docker exec simplementix-backend-1 bench start
13:05:55 system           | redis_cache.1 started (pid=66)
13:05:55 redis_cache.1    | /bin/sh: 1: redis-server: not found
13:05:55 system           | redis_cache.1 stopped (rc=127)
13:05:55 system           | redis_socketio.1 started (pid=69)
13:05:55 redis_socketio.1 | /bin/sh: 1: redis-server: not found
13:05:55 system           | redis_socketio.1 stopped (rc=127)
13:05:55 system           | redis_queue.1 started (pid=76)
13:05:55 redis_queue.1    | /bin/sh: 1: redis-server: not found
13:05:55 system           | redis_queue.1 stopped (rc=127)
13:05:55 system           | watch.1 started (pid=78)
13:05:55 system           | web.1 started (pid=75)
13:05:55 system           | schedule.1 started (pid=82)
13:05:55 system           | socketio.1 started (pid=81)
13:05:55 system           | worker.1 started (pid=88)
13:05:55 system           | sending SIGTERM to web.1 (pid 75)
13:05:55 system           | sending SIGTERM to socketio.1 (pid 81)
13:05:55 system           | sending SIGTERM to watch.1 (pid 78)
13:05:55 system           | sending SIGTERM to schedule.1 (pid 82)
13:05:55 system           | sending SIGTERM to worker.1 (pid 88)
13:05:55 system           | schedule.1 stopped (rc=-15)
13:05:55 system           | web.1 stopped (rc=-15)
13:05:55 system           | watch.1 stopped (rc=-15)
13:05:55 system           | worker.1 stopped (rc=-15)
13:05:55 system           | socketio.1 stopped (rc=-15)

```
