### ISSUE TITLE
Frappe docker not setting Set-Cookie headers as secure

### ISSUE THREAD

**Issue by christulsi** [frappe/frappe_docker#1176]
using the frappe docker setup for production isn't setting the Set-cookie header as secure.

**Comment by revant** [comment]
handle it at the ingress / lb. Following annotation works for ingress based on nginx ingress controller

docs: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#proxy-cookie-path

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ...
    nginx.ingress.kubernetes.io/proxy-cookie-path: |
      / "/; HTTPOnly; Secure; SameSite=strict"
```

For traefik go through header related docs https://doc.traefik.io/traefik/middlewares/http/headers/#configuration-options
