### ISSUE TITLE
Item import not working

### ISSUE THREAD

**Issue by mogupta** [frappe/frappe_docker#1245]
## Description of the issue
Item import not working. I have just installed a fresh ERP next using docker swarm. Using the pwd.yml docker file provided .
When I remove all errors , hit Start import I see a {message: false} response in the network console

## Steps to reproduce the issue

1. Traefik setup
```
frontend:
    image: frappe/erpnext:v14
    deploy:
      restart_policy:
        condition: on-failure
      placement:
              constraints: [node.hostname == eu4]    
      labels:
        - traefik.docker.network=tinxy-net
        - traefik.http.services.erpnext.loadbalancer.server.port=8080    
        - traefik.http.middlewares.erpnext-middle.redirectscheme.scheme=https
        - traefik.http.middlewares.erpnext-middle.redirectscheme.permanent=true

        - traefik.http.routers.erpnext.rule=Host(`erp.mogify.com`)
        - traefik.http.routers.erpnext.entrypoints=web
        - traefik.http.routers.erpnext.middlewares=erpnext-middle

        - traefik.http.routers.erpnext-secure.rule=Host(`erp.mogify.com`)
        - traefik.http.routers.erpnext-secure.tls=true
        - traefik.http.routers.erpnext-secure.tls.certresolver=lets-encrypt            
```
2.  docker stack deploy --compose-file pwd.yml erpnext
3. import item

### Stacktrace / full error message if available

![image](https://github.com/frappe/erpnext/assets/479667/3e757403-fef8-41d1-9830-40377223fce6)

![image](https://github.com/frappe/frappe_docker/assets/479667/8b571e29-b9f2-4609-96fa-e3a9dc4dcf1a)
