### ISSUE TITLE
Add cypress ui test container for running UI tests.

### ISSUE THREAD

**Issue by varun-krishnamurthy** [frappe/frappe_docker#1248]
**Is your feature request related to a problem? Please describe.**
Currently the docker based development doesn't fully support bench run-ui-tests command forcing me to use VM based development. Docker Compose needs to allow running both headful and headless UI testing

**Describe the solution you'd like**
Add a cypress:included service in the devcontainer docker compose file with necessary mounts so that tests can be executed. For using the cypress UI, we need X11 on ubuntu and have to export the DISPLAY variable. It will be also helpful if scripts to install openbox and x11 are available. 

**Describe alternatives you've considered**
VM based development

**Additional context**

Note: I will raise a PR for this one.

**Comment by revant** [comment]
I make following changes in case I need `X` in browser:

```yaml
  # For testing cypress in devcontainers
  x11-bridge: # https://github.com/JAremko/docker-x11-bridge
    image: jare/x11-bridge
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    ports:
      - "8888:8888"
    restart: always
    environment:
      MODE: tcp
      XPRA_HTML: "yes"
      DISPLAY: ":14"
      XPRA_TCP_PORT: "8888"
      XPRA_PASSWORD: admin # This password can be anything you want.

  frappe:
    image: frappe/bench:latest
    command: ["tail", "-f", "/dev/null"]
    environment:
      - SHELL=/bin/bash
      # For cypress testing
      - DISPLAY=:14
      - LIBGL_ALWAYS_INDIRECT=0
    volumes:
      - ..:/workspace:cached
      - ${HOME}/.ssh:/home/frappe/.ssh
    working_dir: /workspace/development
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005
    volumes_from:
      - x11-bridge:rw
    depends_on:
      - x11-bridge
```
