### ISSUE TITLE
WebSockets / socket.io issue with default docker compose setup

### ISSUE THREAD

**Issue by LinoBert** [frappe/frappe_docker#1481]
## Description of the issue
Running the getting started docker steps, the system works as expected, but the websocket connection to the frontend container can not be established.

The issue seems very similar to the question reported in this issue: #1456 but the same is happening for the default configuration without any changes to the docker compose file.

## Context information (for bug reports)
image: frappe/erpnext:v15.37.0

docker compose frontend definition
```
  frontend:
    image: frappe/erpnext:v15.37.0
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8080:8080"


  websocket:
    image: frappe/erpnext:v15.37.0
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
```

### Observed result
Websocket connection is not established in Chrome/Firefox on ws://localhost:8080/socket.io

### Stacktrace / full error message if available
![image](https://github.com/user-attachments/assets/af1a4918-c8f5-4ffd-9d43-ff33a8aef0d0)

```
Firefox can’t establish a connection to the server at ws://localhost:8080/socket.io/?EIO=4&transport=websocket&sid=Ztwt9rAp4D6aoLbcAAAA.

The connection to ws://localhost:8080/socket.io/?EIO=4&transport=websocket&sid=Ztwt9rAp4D6aoLbcAAAA was interrupted while the page was loading.
```
