### ISSUE TITLE
How to attach custom ssl certificate to frappe site?

### ISSUE THREAD

**Issue by abhishek-bankar** [frappe/frappe_docker#1557]
Please help me to attach ssl certificate to traefik, portainer and frappe site. I have custom ssl certificates. I followed the tutorial of deploying frappe in production with custom apps. It is working fine but I am not able to attach ssl certificates. I have valid .crt and .key files.

**Comment by revant** [comment]
Check traefik community and docs 
https://community.traefik.io/t/how-to-use-own-ssl-certificate/20209

**Comment by abhishek-bankar** [comment]
Thanks @revant. It worked. Traefik uses dynamic configuration for attaching own ssl certificate. Just we have to give path for certificate in dynamic configuration file.

**dynamic_conf.yml**

```
tls:
  certificates:
    - certFile: "/ssl/server.crt"
      keyFile: "/cert/server_no_pass.key"
```

**traefik.yml**
```
services:
  traefik:
    image: traefik:${TRAEFIK_VERSION:-v3.3}
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      placement:
        constraints:
          # Required for the TLS certificates
          - node.labels.traefik-public.traefik-public-certificates == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.middlewares.admin-auth.basicauth.users=admin:${HASHED_PASSWORD?Variable not set}
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.traefik-public-http.rule=Host(`${TRAEFIK_DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        - traefik.http.routers.traefik-public-https.rule=Host(`${TRAEFIK_DOMAIN}`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        - traefik.http.routers.traefik-public-https.service=api@internal
        - traefik.http.routers.traefik-public-https.middlewares=admin-auth
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
      - /data/devops/ssl:/ssl # Mount the SSL directory into the container
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --providers.file.filename=/ssl/dynamic_conf.yml # Load dynamic config
      - --accesslog
      - --log
      - --api
    networks:
      - traefik-public

volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    name: traefik-public
    attachable: true
```
