### ISSUE TITLE
CSS is going after 2-3 builds

### ISSUE THREAD

**Issue by abhishek-bankar** [frappe/frappe_docker#1572]
I am deploying my custom apps frappe production image using docker swarm and portainer. Initial 4-5 times it works well but after that frappe site does not show any css and raw UI comes without any css. How should I resolve it. I tried clearing cache and old images as well. It does not work. However pipeline build is successful

```
name: FRAPPE BACKEND CI PIPELINE - DEV

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  BUILD_DEV:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    environment: Inventive
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Frappe Docker Repository
        uses: actions/checkout@v4
        with:
          repository: frappe/frappe_docker
          path: builds

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: builds
          file: builds/${{ vars.DOCKERFILE_PATH }}
          tags: |
            ${{ vars.IMAGE_NAME }}:${{ github.sha }}
            ${{ vars.IMAGE_NAME }}:latest
          build-args: |
            "FRAPPE_PATH=${{ vars.FRAPPE_REPO }}"
            "FRAPPE_BRANCH=${{ vars.FRAPPE_VERSION }}"
            "PYTHON_VERSION=${{ vars.PYTHON_VERSION }}"
            "NODE_VERSION=${{ vars.NODEJS_VERSION }}"
            "APPS_JSON_BASE64=${{ vars.APPS_JSON_BASE64 }}"
```

<img width="833" alt="Image" src="https://github.com/user-attachments/assets/3c997327-a2d2-49e9-99af-8b880ef4143c" />
