### ISSUE TITLE
How to create user on docker compose startup

### ISSUE THREAD

**Issue by huksley** [frappe/frappe_docker#1575]
I want to run docker compose setup and create a predefined user with username and password I specifiy in env variables. How I can do that?

Something like this???

```yaml
configurator:
    command:
        bench example-set-username ${ADMIN_EMAIL}
        bench example-set-password ${ADMIN_PASSWORD}
```
