### ISSUE TITLE
Deployment issue while installing frappe/education

### ISSUE THREAD

**Issue by rabbitholeseek** [frappe/frappe_docker#1617]
![Image](https://github.com/user-attachments/assets/a16b1924-0eea-4c48-b4ac-5a312f163d5b)
Step 2: Run the deployment command

Got issues while executing the above step from frappe education installation guide. I have properly replaced email and subdomain.domain.tld link. Is there any pre-requisites even before this? Docker is already installed and I believe the script takes care of checking if its installed or not. What should I do to ensure it's installed correctly?

Additionally, when I ran the same command with "sudo" , it threw another issue.

Cmd:
```
python3 ./easy-install.py deploy \
    --project=education_prod_setup \
    --email=your_email.example.com \
    --image=ghcr.io/frappe/education \
    --version=stable \
    --app=education \
    --sitename subdomain.domain.tld
```

![Image](https://github.com/user-attachments/assets/c4d2928c-08ba-4726-acd8-8d24d88a1891)

**Comment by tikmku** [comment]
you can try our custom image
it contains erpnext, education app and hrms app
https://hub.docker.com/r/tikmku/erpnext-education

just use single compose from this repo
https://github.com/frappe/frappe_docker/blob/main/pwd.yml

we use this image in 'production', managing our small school

**Comment by rabbitholeseek** [comment]
Umm, could you guide me through it? I'm not a coder or technical enough person to do all vps installation without any errors heh

**Comment by tikmku** [comment]
try to use <version> tag
`
docker pull tikmku/erpnext-education:2.1.1
`

**Comment by revant** [comment]
I guess you've missed some steps after docker setup. 


https://docs.docker.com/engine/install/linux-postinstall/

**Comment by rabbitholeseek** [comment]
> I guess you've missed some steps after docker setup.
> 
> https://docs.docker.com/engine/install/linux-postinstall/

No I've already done that.. still will redo for double check, thank you.

**Comment by rabbitholeseek** [comment]
> you can try our custom image it contains erpnext, education app and hrms app https://hub.docker.com/r/tikmku/erpnext-education
> 
> just use single compose from this repo https://github.com/frappe/frappe_docker/blob/main/pwd.yml change 80th line, into ` bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --install-app education --install-app hrms --set-default frontend;`
> 
> we use this image in 'production', managing our small school

could I personally contact you, if you could help me deploying it please? I tried for two days with chatgpt but alas it didnt go well

**Comment by rabbitholeseek** [comment]
![Image](https://github.com/user-attachments/assets/105ccac0-ffca-49d5-8e31-301156d9140c)

now edu module is having some issue (using bench scripts), im really troubled by this, tried reinstalling removing cache everything

**Comment by tikmku** [comment]
@rabbitholeseek share your docker-compose.yml
or did you used the 'original' pwd.yml?

**Comment by rabbitholeseek** [comment]
> [@rabbitholeseek](https://github.com/rabbitholeseek) share your docker-compose.yml or did you used the 'original' pwd.yml?

i changed pwd.yml according to your comment, but it fails, im frustrated from 2 days im at this

**Comment by tikmku** [comment]
Hey @rabbitholeseek 
I've prepared a custom pwd.yml file for you with the following setup:

- Run on port 8080, http://your-ip-address:8080
- ERPNext, HRMS, and Education are already installed
- The Administrator password is set to 'admin' by default — feel free to change it anytime
- Please delete any previous ERPNext Education container you’ve created before running this pwd.yml
- Also, don’t forget to remove its storage/volumes to avoid conflicts

Let me know if you run into any issues!

```
version: "3"

services:
  backend:
    image: tikmku/erpnext-education:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  configurator:
    image: tikmku/erpnext-education:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: tikmku/erpnext-education:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;
        export start=`date +%s`;
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created";
          sleep 5;
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys";
            exit 1
          fi
        done;
        echo "sites/common_site_config.json found";
        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --install-app hrms --install-app education --set-default frontend;

  db:
    image: mariadb:10.6
    networks:
      - frappe_network
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 20
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: tikmku/erpnext-education:latest
    networks:
      - frappe_network
    depends_on:
      - websocket
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "60080:8080"

  queue-long:
    image: tikmku/erpnext-education:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  queue-short:
    image: tikmku/erpnext-education:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure

  scheduler:
    image: tikmku/erpnext-education:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: tikmku/erpnext-education:latest
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  redis-queue-data:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
```
