### ISSUE TITLE
Docker-Compose: Can't read dir of '/etc/mysql/mariadb.conf.d/'

### ISSUE THREAD

**Issue by emcniece** [frappe/frappe_docker#2]
During `docker-compose up -d` the `mariadb` container throws an error:

```
mariadb           | /usr/sbin/mysqld: Can't read dir of '/etc/mysql/mariadb.conf.d/' (Errcode: 2 "No such file or directory")
```

Looks like the volume needs to be updated in `docker-compose.yml`:

From:

```
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3307" #mariadb-port
    container_name: mariadb
```

To:

```
  mariadb:
    image: "mariadb"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./conf/mariadb-conf.d:/etc/mysql/mariadb.conf.d
    ports:
      - "3307:3307" #mariadb-port
    container_name: mariadb
```

The MariaDB container works fine after this.
