### ISSUE TITLE
Sign up broken on edge

### ISSUE THREAD

**Issue by NickBusey** [frappe/frappe_docker#208]
## Description of the issue

Sign up is broken on a new install.

## Context information (for bug reports)

Using this docker-compose file:

```
---
version: '3'

# This networks section required for the pacakge to be visible to Traefik.
# DO NOT Remove
networks:
  traefik_network:
    external:
      name: homelabos_traefik

services:
  redis-cache:
    networks:
      - traefik_network
    image: redis:latest
    restart: on-failure
    volumes:
      - "/var/homelabos/erpnext/redis-cache-vol:/data"

  redis-queue:
    networks:
      - traefik_network
    image: redis:latest
    restart: on-failure
    volumes:
      - "/var/homelabos/erpnext/redis-queue-vol:/data"

  redis-socketio:
    networks:
      - traefik_network
    image: redis:latest
    restart: on-failure
    volumes:
      - "/var/homelabos/erpnext/redis-socketi-vol:/data"

  mariadb:
    networks:
      - traefik_network
    image: mariadb:10.3
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "/var/homelabos/erpnext/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf"
      - "/var/homelabos/erpnext/mariadb-vol:/var/lib/mysql"

  erpnext-nginx:
    image: frappe/erpnext-nginx:${VERSION}
    restart: on-failure
    environment:
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
      - LETSENCRYPT_HOST=${SITES}
      - VIRTUAL_HOST=${SITES}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - erpnext-python
      - frappe-socketio
      - frappe-worker-default
      - frappe-worker-long
      - frappe-worker-short
    links:
      - erpnext-python
      - frappe-socketio
      - frappe-worker-default
      - frappe-worker-long
      - frappe-worker-short
    volumes:
      - "/var/homelabos/erpnext/sites:/var/www/html/sites"
      - "/var/homelabos/erpnext/assets-vol:/assets"
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=homelabos_traefik"
      - "traefik.http.services.erpnext.loadbalancer.server.scheme=http"
      - "traefik.http.services.erpnext.loadbalancer.server.port=80"
      - "traefik.http.routers.erpnext-http.rule=Host(`erpnext.grownetics413.local`)"
      - "traefik.http.routers.erpnext-http.entrypoints=http"
      - "traefik.http.routers.erpnext-http.middlewares=customFrameHomelab@file"
      - "traefik.http.routers.erpnext.rule=Host(`erpnext.grownetics413.local`)"
      - "traefik.http.routers.erpnext.entrypoints=https"
      - "traefik.http.routers.erpnext.middlewares=customFrameHomelab@file"
      - "traefik.http.routers.erpnext.tls=true"
      - "traefik.http.routers.erpnext.tls.certresolver=http"

  erpnext-python:
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    networks:
      - traefik_network
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SOCKETIO_PORT=9000
      - AUTO_MIGRATE=1
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"
      - "/var/homelabos/erpnext/assets-vol:/home/frappe/frappe-bench/sites/assets"

  frappe-socketio:
    networks:
      - traefik_network
    image: frappe/frappe-socketio:${VERSION}
    restart: on-failure
    depends_on:
      - redis-socketio
    links:
      - redis-socketio
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"


  frappe-worker-default:
    networks:
      - traefik_network
    image: frappe/erpnext-worker:${VERSION}
    restart: on-failure
    command: worker
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"

  frappe-worker-short:
    image: frappe/erpnext-worker:${VERSION}
    networks:
      - traefik_network
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=short
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"

  frappe-worker-long:
    image: frappe/erpnext-worker:${VERSION}
    networks:
      - traefik_network
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=long
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"

  frappe-schedule:
    image: frappe/erpnext-worker:${VERSION}
    networks:
      - traefik_network
    restart: on-failure
    command: schedule
    depends_on:
      - redis-queue
      - redis-cache
    links:
      - redis-queue
      - redis-cache
    volumes:
      - "/var/homelabos/erpnext/sites:/home/frappe/frappe-bench/sites"
```

## Steps to reproduce the issue

1. Try to register. It fails.

### Observed result

Be able to register.

### Expected result

Cannot register.

### Stacktrace / full error message if available

```
exc: ["Traceback (most recent call last):\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/app.py\", line 59, in application\n    response = frappe.handler.handle()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/handler.py\", line 24, in handle\n    data = execute_cmd(cmd)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/handler.py\", line 63, in execute_cmd\n    return frappe.call(method, **frappe.form_dict)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1074, in call\n    return fn(*args, **newargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py\", line 779, in sign_up\n    user.insert()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 264, in insert\n    self.run_post_save_methods()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 938, in run_post_save_methods\n    self.run_method(\"on_update\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 805, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 1091, in composer\n    return composed(self, method, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 1074, in runner\n    add_to_return_value(self, fn(self, *args, **kwargs))\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 799, in <lambda>\n    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py\", line 100, in on_update\n    self.send_password_notification(self.__new_password)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py\", line 209, in send_password_notification\n    self.send_welcome_mail_to_user()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py\", line 275, in send_welcome_mail_to_user\n    site_url=get_url(),\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py\", line 301, in send_login_mail\n    delayed=(not now) if now!=None else self.flags.delay_emails, retry=3)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 495, in sendmail\n    inline_images=inline_images, header=header, print_letterhead=print_letterhead)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/email/queue.py\", line 77, in send\n    sender = email_account.default_sender\nAttributeError: 'NoneType' object has no attribute 'default_sender'\n"]
```
