### ISSUE TITLE
Reverse Proxy: Error in socketio requests - it refers to sitename instead of hostname

### ISSUE THREAD

**Issue by paulator** [frappe/frappe_docker#231]
## Description of the issue
In my dockerized setup with a reverse proxy in front of ERPNext, I have error message in the logfile in the container `frappe-socketio`. It can't access the host with the name of the ERPNext site name.

## Context information (for bug reports)
On my system I install ERPNext with the official docker images. There is already a nginx included but I opted to connect the erpnext-nginx to a Traefik reverse proxy to fit to the overall architecture.

# Setup:
* I set up everything on version-11 images
* I created a site called `site1.local` in erpnext
* The Traefik reverse proxy listens to the public host name of the server (e.g. https://erp.example.com)
* Traefik modifies the `host` header of the request from erp.example.com to site1.local

--> Then I'm able to access my ERPNext instance through Traefik (this is the expected behavior)

## Steps to reproduce the issue

1. Setup dockerized ERPNext
2. Setup traefik
3. Connect traefik with erpnext-nginx and set the header `host` to the value of the site

In my case I use Traefik 2.2 with this labels on the erpnext-nginx container - development, without ssl:

```
  erpnext-nginx:
    image: frappe/erpnext-nginx:${VERSION}
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.erpnext_insecure.rule=Host(`erpnext.example.com`)"
      - "traefik.http.routers.erpnext_insecure.entrypoints=http"
      - "traefik.http.routers.erpnext_insecure.service=erpnext_insecure@docker"
      - "traefik.http.services.erpnext_insecure.loadbalancer.server.port=80"
      - "traefik.http.middlewares.hostname.headers.customrequestheaders.host=site1.local"
      - "traefik.http.routers.erpnext_insecure.middlewares=hostname"
```

### Observed result
* In the logfile I get the error as shown in the stacktrace
* socketio do use the sitename instead of the hostname of the request
### Expected result
* let socketio use the hostname of the request

### Stacktrace / full error message if available

```
 Error: getaddrinfo ENOTFOUND site1.local
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
   errno: -3008,
   code: 'ENOTFOUND',
   syscall: 'getaddrinfo',
   hostname: 'site1.local',
   response: undefined
 }
```
