### ISSUE TITLE
Help wanted for making docker easy to run

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#353]
Help wanted for making docker easy to run on:

- TLDR setup, I tried with docker-compose.yml, I'm out of ideas now.
- Linux
- Linux with custom kernels
- Mac
- Windows Pro
- Windows Home
- Virtualbox/VMWare/KVM/XEN/lxd/other VMs available.
- System where port 80 and port 443 are already used, (other complex port mapping may also be done already on host machine) https://github.com/frappe/frappe_docker/issues/354
- Think of more complex scenarios and provide for it in docs. e.g Docker in Linux VM on Windows Server access through VPN
- The installation should be accessible on LAN/WAN/Private network.
- ARM devices

I don't know how to help others with this.

**Comment by ceefour** [comment]
Hi @revant ,

Unless you see any concerns with this, I figure might as well make `frappe_docker` repo (and hopefully `frappe` and `erpnext` as well) Hacktoberfest-eligible since DigitalOcean changed to an opt-in model this year: https://hacktoberfest.digitalocean.com/details#details

Requires adding a [hacktoberfest](https://github.com/topics/hacktoberfest) topic to the repo on GitHub, that should be all that's necessary for this.

**Comment by christf** [comment]
I am struggling with the setup of erpnext inside docker using docker-compose. based on the env-local file I have created the pods, they are coming up with an .env file based on the local one and when I curl http://myhostname I get an http 404 error.

**Comment by Davincible** [comment]
Hi @revant , I am willing to help write out the docker documentation better. The only issues is that I myself am still getting the permisison denied error as has been mentioned throughout the forum and github issues. 

I have some ideas on how to improve the documentation, and make it easier to install, but I first need to get my own image working. If you have any suggestions for the permission error I am keen to hear it.

**Comment by revant** [comment]
Permission error is because the process in container runs as frappe user (non-root user)

The volume mounted by root with root permission causes the problem.

Exec into python container and run

```sh
chown -R frappe:frappe /home/frappe/frappe-bench/sites
```

This step is generally not needed.

**Comment by senorsmile** [comment]
I have just discovered erpnext and am trying to bring it up to play with. 

I am also getting a 404, specifically (with my.domain.com representing my actual sub domain pointed to the machine where this is installed): 
```Not Found
my.domain.com does not exist
```

I've poked around the nginx container, but don't see anything obvious.  
I tried poking around the python container.  I see proc /proc/1/ running, but not much I can do without being root. 

Any idea what is going wrong following the current directions?

**Comment by Davincible** [comment]
@senorsmile Yeah you need to forward the headers, was also stuck on that problem for way too long. My config:
```
    location / {
        proxy_pass http://localhost:8060;
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass_request_headers      on;
    }
```

**Comment by revant** [comment]
PR related to nginx config. Check if setting env variables solves your problem.

https://github.com/frappe/frappe_docker/pull/419

**Comment by shareef** [comment]
> Permission error is because the process in container runs as frappe user (non-root user)
> 
> The volume mounted by root with root permission causes the problem.
> 
> Exec into python container and run
> 
> ```shell
> chown -R frappe:frappe /home/frappe/frappe-bench/sites
> ```
> 
> This step is generally not needed.

I saw the sites are owned by root, when I ran the command I am getting Operation not permitted error.

**Comment by senorsmile** [comment]
@revant 

I added ```UPSTREAM_REAL_IP_ADDRESS='192.168.1.100'``` to .env. 
I also had to add ```      - UPSTREAM_REAL_IP_ADDRESS``` to the docker-compose.yml under  
```  erpnext-nginx:
    image: frappe/erpnext-nginx:${ERPNEXT_VERSION}
    restart: on-failure
    environment:
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
      - UPSTREAM_REAL_IP_ADDRESS
```

I now see that being set in the nginx config.  
However, I'm still getting page not found.  


@Davincible I assume that you built a custom image with this config?

**Comment by shareef** [comment]
Folks, I spent good amount of time making the docker-compose stable for dev environment. I am able to compose the containers and dependencies properly so the containers start working with get go. No more config not found, restarts etc...

How can I contribute to this project?

**Comment by ddavidebor** [comment]
Open a PR! Contributions welcome :-)

**Comment by Davincible** [comment]
@shareef oeh that sounds juicy, could you also put it in a public repo?

**Comment by Davincible** [comment]
@senorsmile I linked the nginx container to my host instead of the python container, as the nginx container is used to serve static content:
```
  erpnext-nginx:
    image: frappe/erpnext-nginx:${ERPNEXT_VERSION}
    restart: on-failure
    environment:
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erpnext-nginx.rule=Host(${SITES})"
      - "${ENTRYPOINT_LABEL}"
    # - "${CERT_RESOLVER_LABEL}"
      - "traefik.http.services.erpnext-nginx.loadbalancer.server.port=80"
    ports:
      - "8060:80"
    volumes:
      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw
      - /var/run/mysqld:/mariadb_socket
```

And then comment out the Traefik image
