### ISSUE TITLE
Automatic database backup feature doesn't seem to work in single bench install.

### ISSUE THREAD

**Issue by hazkaz** [frappe/frappe_docker#405]
### What I've tried
I've tried installing `edge` and `version-12` of erpnext with the instructions given in [single bench](https://github.com/frappe/frappe_docker/blob/761f8345d7e3d78da62200bb040402c9dd423d0b/docs/single-bench.md). The automatic backups (available at http:/ip-address/desk#backups) are not working. The UI appears as an empty table.

I've tried deploying with easy_install script and that seems to be making the backups properly.

### Details
Could you help me narrow down where the problem could be? Here are some possibly relevant details:
1. I've deployed on digitalocean with a configuration similar to env-local.
2. No Domain is present. I'm working off of a IP address
3. manual backup using `docker run -e .....` command seems to work

**Comment by agritheory** [comment]
Test this manually by running 'bench backup' inside the container (sounds like you've done this already) and the force refreshing (CTRL-SHIFT-R) on the /backups browser page.

**Comment by hazkaz** [comment]
#### More details as per @agritheory 's suggestions:
1. yes I had run the `docker run -e ... backup` command earlier and it created 1 backup before which there were no backups. I think erpnext creates a backup soon after deploying if I'm not wrong; but that didn't happen in my case.
2. after I got into the container `site-name-erpnext-worker_default1` and ran `bench --site ip-address backup` , it created an additional backup(total 2) , but they didn't show up in the ui despite force refreshing.
3. to rule out stupidity on my part - let me say that I've currently deployed the application with `SITE_NAME` and `SITES` in .env set as the public ip address. This is the only way I could get the app running without a domain name. I hope this is the correct way to do it.

**Comment by revant** [comment]
I'm able to see backups on my production instances running on k8s

v12 (screenshot below):

![erpnext-backups-v12](https://user-images.githubusercontent.com/1040161/104666974-1f7d0880-56fb-11eb-80ef-6ffa7ae2655b.png)

v13-beta (screenshot below):

![erpnext-backups-v13-beta](https://user-images.githubusercontent.com/1040161/104667192-87335380-56fb-11eb-9c6a-424ac93ba731.png)

**Comment by revant** [comment]
> 3\. to rule out stupidity on my part - let me say that I've currently deployed the application with `SITE_NAME` and `SITES` in .env set as the public ip address. This is the only way I could get the app running without a domain name. I hope this is the correct way to do it.

What you're trying to replicate here is behaviour that is seen by setting default site.

If you understand docker this is what is done here (the stack that gets deployed as Play with docker):

https://raw.githubusercontent.com/frappe/frappe_docker/develop/tests/pwd.yml

Things to notice in the file:

```yaml
  erpnext-nginx:
    ...
    deploy:
      ...
      labels:
        ...
        - "traefik.http.routers.erpnext-nginx.rule=HostRegexp(`{catchall:.*}`)"
        - "traefik.http.middlewares.erpnext-nginx.headers.customrequestheaders.Host=erpnext-nginx"
        - "traefik.http.routers.erpnext-nginx.middlewares=erpnext-nginx"
        ...
  site-configurator:
    image: frappe/erpnext-worker:edge
    deploy:
      restart_policy:
        condition: none
    command: ["bash", "-c", "echo erpnext-nginx > /sites/currentsite.txt"]
    volumes:
      - sites-vol:/sites:rw
```

check the labels of erpnext-nginx container and additional container called site-configurator

This will result into all routes serving single site from the setup.
