### ISSUE TITLE
Allow docker userns_remap feature: add `userns_mode: "host"` to traefik service.

### ISSUE THREAD

**Issue by Dave3o3** [frappe/frappe_docker#420]
**Is your feature request related to a problem? Please describe.**
When making use of the docker [user name space remapping feature](https://docs.docker.com/engine/security/userns-remap/) to isolate container environments, the traefik service will not be able to access the docker socket.

**Describe the solution you'd like**
Adding `userns_mode: "host"` to the traefik service definition in docker-compose.yml solves this problem.

```yaml

version: "3"

services:
  traefik:
    image: "traefik:v2.2"
   #[...]
    volumes:
      - cert-vol:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    userns_mode: "host" # <--- this will resolve the issue

```

**Describe alternatives you've considered**
Running docker service as root user, which isn't always an alternative.
