### ISSUE TITLE
Problem with Development configuration using ./devcontainer-example/docker-compose.yml

### ISSUE THREAD

**Issue by Ciangi** [frappe/frappe_docker#446]
## Description of the issue
Follow steps from README `https://github.com/frappe/frappe_docker/tree/develop/development`

in Step about creating site got error:

```
For key character_set_server. Expected value utf8mb4, found value latin1
For key collation_server. Expected value utf8mb4_unicode_ci, found value latin1_swedish_ci
================================================================================
Creation of your site - erpmain.localhost failed because MariaDB is not properly 
configured.  If using version 10.2.x or earlier, make sure you use the 
the Barracuda storage engine. 

Please verify the settings above in MariaDB's my.cnf.  Restart MariaDB.  And 
then run `bench new-site erpmain.localhost` again.
```

Solution:

in `docker-compose.yml` added:

```
version: "3.7"
services:
  mariadb:
    image: mariadb:10.3
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

(...)
```
