### ISSUE TITLE
Problem with creating custom erpnext_documentation docker-compose

### ISSUE THREAD

**Issue by Ciangi** [frappe/frappe_docker#466]
## Description of the issue
Hi,

 i would like to get Home page of erpnext_documentation as it is described [here](https://github.com/frappe/erpnext/wiki/How-To-Contribute-to-the-ERPNext-Documentation-(The-Lengthy-Version)#2-install-new-site-and-the-app).

The problem is that when i login to my site, i got home page "Login to Frappe".

## Steps to reproduce the issue
my docker-compose:

```
version: "3.7"
services:
  erp-doc:
    image: erp-nginx
    command: sleep infinity
    environment:
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
    volumes:
      - ./sites:/var/www/html/sites:rw
      - ./assets:/assets:rw
    ports:
      - "8050:80"

  erpnext-python:
    image: erp-worker
    restart: on-failure
    environment:
      - MARIADB_HOST=mariadb
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SOCKETIO_PORT=9000
      - AUTO_MIGRATE=1
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites:rw
      - ./assets:/home/frappe/frappe-bench/sites/assets:rw

  mariadb:
    image: mariadb:10.3
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - ./mariadb:/var/lib/mysql

  frappe-socketio:
    image: frappe/frappe-socketio:develop
    restart: on-failure
    depends_on:
      - redis-socketio
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites:rw

  erpnext-schedule:
    image: erp-worker
    restart: on-failure
    command: schedule
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites:rw
      - ./logs:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-long:
    image: erp-worker
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=long
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites:rw

  erpnext-worker-short:
    image: erp-worker
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=short
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites:rw
      - ./logs:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-default:
    image: erp-worker
    restart: on-failure
    command: worker
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites:rw
      - ./logs:/home/frappe/frappe-bench/logs:rw


  redis-cache:
    image: redis:latest
    restart: on-failure

  redis-queue:
    image: redis:latest
    restart: on-failure

  redis-socketio:
    image: redis:latest
    restart: on-failure

  # site-creator:
  #   image: erp-worker
  #   restart: "no"
  #   command: new
  #   depends_on:
  #     - erpnext-python
  #   environment:
  #     - SITE_NAME=erpdoc.mydomain.com
  #     - DB_ROOT_USER=root
  #     - MYSQL_ROOT_PASSWORD=123
  #     - ADMIN_PASSWORD=admin
  #     - INSTALL_APPS=erpnext_documentation
  #   volumes:
  #     - ./sites:/home/frappe/frappe-bench/sites:rw
```

erp-nginx image created from [Dockerfile](https://github.com/frappe/erpnext_documentation/blob/master/.deploy/build/erpnext-docs-nginx/Dockerfile)
erp-worker image created from [Dockerfile](https://github.com/frappe/erpnext_documentation/blob/master/.deploy/build/erpnext-docs-worker/Dockerfile)

So, i run once `site-creator` container to create new site.  Then opened page `erpdoc.mydomain.com` and got Login to Frappe instead of erpnext_documentation page.

Btw. when i run `docker-compose up` firstly i got 500 Internal Server Error when tried to login `erpdoc.mydomain.com`, i noticed that inside `erp-doc` container `service nginx status` is `nginx is not running` so manually start it using command `nginx`.

I tried also login to `erpnext-python` container and run
 `install_app frappe_theme https://github.com/frappe/frappe_theme`
`bench --site erpdoc.mydomain.com install_app erpnext_documentation`
 `bench --site erpdoc.mydomain.com migrate` 

but still got only Frappe Login Page. What im doing wrong?

**Comment by revant** [comment]
if you want to contribute to docs or any app use the development setup.

https://github.com/frappe/frappe_docker/tree/develop/development

**Comment by Ciangi** [comment]
`docker-compose.yml`:

```
version: "3.7"
services:
  mariadb:  
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
    volumes:
      - ./frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - ./db:/var/lib/mysql

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: sleep infinity
    volumes:
      - ./workspace:/workspace:cached
    working_dir: /workspace/development
    ports:
      - "8050:8000"
      - "9050:9000"
```

inside `frappe` container:

`history`:

```
   bench init --skip-redis-config-generation --frappe-branch version-12 frappe-bench
   cd frappe-bench/
   bench set-mariadb-host mariadb
   bench set-redis-cache-host redis-cache:6379
   bench set-redis-queue-host redis-queue:6379
   bench set-redis-socketio-host redis-socketio:6379
   sed -i '/redis/d' ./Procfile
   bench get-app https://github.com/frappe/erpnext_documentation
   bench get-app frappe_theme
   bench start
```

As is is written [here](https://github.com/frappe/erpnext/wiki/How-To-Contribute-to-the-ERPNext-Documentation-(The-Lengthy-Version)#2-install-new-site-and-the-app)
 i run `bench start` and opened new tab in frappe container and run:
```
bench new-site erp.mydomain.com
bench --site erp.mydomain.com install-app erpnext_documentation
```

Then tried to open page `erp.mydomain.com` and still Frappe login page.
