### ISSUE TITLE
The erpnext containers keep restarting

### ISSUE THREAD

**Issue by mohammedfarish** [frappe/frappe_docker#483]
Here's what I got when I entered `docker ps` in the terminal.
```bash
CONTAINER ID   IMAGE                         COMMAND                  CREATED          STATUS                          PORTS                                      NAMES
4d7253a87e7a   frappe/erpnext-worker:edge    "docker-entrypoint.s…"   19 minutes ago   Restarting (1) 13 seconds ago                                              frappe_docker_erpnext-worker-long_1
a891b24624b2   frappe/erpnext-worker:edge    "docker-entrypoint.s…"   19 minutes ago   Restarting (1) 17 seconds ago                                              frappe_docker_erpnext-schedule_1
724a29350478   frappe/erpnext-worker:edge    "docker-entrypoint.s…"   19 minutes ago   Restarting (1) 15 seconds ago                                              frappe_docker_erpnext-worker-short_1
4602ddec2400   frappe/erpnext-worker:edge    "docker-entrypoint.s…"   19 minutes ago   Restarting (1) 17 seconds ago                                              frappe_docker_erpnext-worker-default_1
ee2c035d6f6c   frappe/frappe-socketio:edge   "docker-entrypoint.s…"   19 minutes ago   Restarting (1) 22 seconds ago                                              frappe_docker_frappe-socketio_1
5bb575ceb1ab   frappe/erpnext-nginx:edge     "/docker-entrypoint.…"   19 minutes ago   Restarting (1) 31 seconds ago                                              frappe_docker_erpnext-nginx_1
e76805def8da   redis:latest                  "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes                   6379/tcp                                   frappe_docker_redis-cache_1
cab5a593883a   redis:latest                  "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes                   6379/tcp                                   frappe_docker_redis-socketio_1
03acf71f3cc7   redis:latest                  "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes                   6379/tcp                                   frappe_docker_redis-queue_1
6933189f7e79   frappe/erpnext-worker:edge    "docker-entrypoint.s…"   19 minutes ago   Restarting (1) 24 seconds ago                                              frappe_docker_erpnext-python_1
bb4c4ea08513   traefik:v2.2                  "/entrypoint.sh --lo…"   19 minutes ago   Up 19 minutes                   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   frappe_docker_traefik_1
628d99b07b3f   mariadb:10.3                  "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes                   3306/tcp                                   frappe_docker_mariadb_1
```

**Comment by revant** [comment]
Can you share logs of restarting containers.

Don't use edge images in production setup

**Comment by mohammedfarish** [comment]
here's the log
```bash
standard_init_linux.go:219: exec user process caused: exec format error
```
They're all having the same log error message.

**Comment by revant** [comment]
https://discuss.erpnext.com/t/docker-installation/76304/4

Sorry I can’t help.

Can you share your docker-compose file if someone else can find anything?

**Comment by revant** [comment]
I really think docker only works on my computer

**Comment by mohammedfarish** [comment]
The docker file remains unedited. but here's a copy of it, for your refference.

```yml
version: "3"

services:
  traefik:
    image: "traefik:v2.2"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      # enable traefik
      - "traefik.enable=true"
      # global redirect to https for production only
      - "${HTTPS_REDIRECT_RULE_LABEL}"
      - "${HTTPS_REDIRECT_ENTRYPOINT_LABEL}"
      - "${HTTPS_REDIRECT_MIDDLEWARE_LABEL}"
      # middleware redirect for production only
      - "${HTTPS_USE_REDIRECT_MIDDLEWARE_LABEL}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert-vol:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    userns_mode: "host"

  erpnext-nginx:
    image: frappe/erpnext-nginx:${ERPNEXT_VERSION}
    restart: on-failure
    environment:
      - FRAPPE_PY=erpnext-python
      - FRAPPE_PY_PORT=8000
      - FRAPPE_SOCKETIO=frappe-socketio
      - SOCKETIO_PORT=9000
      - SKIP_NGINX_TEMPLATE_GENERATION=${SKIP_NGINX_TEMPLATE_GENERATION}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.erpnext-nginx.rule=Host(${SITES})"
      - "${ENTRYPOINT_LABEL}"
      - "${CERT_RESOLVER_LABEL}"
      - "traefik.http.services.erpnext-nginx.loadbalancer.server.port=80"
    volumes:
      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw

  erpnext-python:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SOCKETIO_PORT=9000
      - AUTO_MIGRATE=1
      - WORKER_CLASS=${WORKER_CLASS}
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - assets-vol:/home/frappe/frappe-bench/sites/assets:rw

  frappe-socketio:
    image: frappe/frappe-socketio:${FRAPPE_VERSION}
    restart: on-failure
    depends_on:
      - redis-socketio
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-default:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: worker
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-short:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=short
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  erpnext-worker-long:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: worker
    environment:
      - WORKER_TYPE=long
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw

  erpnext-schedule:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: on-failure
    command: schedule
    depends_on:
      - redis-queue
      - redis-cache
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

  redis-cache:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-cache-vol:/data

  redis-queue:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-queue-vol:/data

  redis-socketio:
    image: redis:latest
    restart: on-failure
    volumes:
      - redis-socketio-vol:/data

  mariadb:
    image: mariadb:10.3
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./installation/frappe-mariadb.cnf:/etc/mysql/conf.d/frappe.cnf
      - mariadb-vol:/var/lib/mysql

  site-creator:
    image: frappe/erpnext-worker:${ERPNEXT_VERSION}
    restart: "no"
    command: new
    depends_on:
      - erpnext-python
    environment:
      - SITE_NAME=${SITE_NAME}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - INSTALL_APPS=${INSTALL_APPS}
    volumes:
      - sites-vol:/home/frappe/frappe-bench/sites:rw
      - logs-vol:/home/frappe/frappe-bench/logs:rw

volumes:
  mariadb-vol:
  redis-cache-vol:
  redis-queue-vol:
  redis-socketio-vol:
  assets-vol:
  sites-vol:
  cert-vol:
  logs-vol:
```
