### ISSUE TITLE
nginx assets location

### ISSUE THREAD

**Issue by zwessels** [frappe/frappe_docker#538]
in the `docker-compose.yml` there is this entry: 

 ```yaml
  erpnext-nginx:
    image: frappe/erpnext-nginx:${ERPNEXT_VERSION}
    ... rest
    volumes:
      - sites-vol:/var/www/html/sites:rw
      - assets-vol:/assets:rw
```      

is there a particular reason why `- assets-vol:/assets:rw` is not pointing to `- assets-vol:/var/www/html/assets:rw`. 

from what i can observe both `/assets` and `/var/www/html/assets` contains the same files, the only difference is that `/assets` is declared as a volume in the `Dockerfile` for nginx.

reason i am asking is because if i add a file inside the nginx container under `/var/www/html/assets/hello-world.js` , then i can access it via `http://mysite/assets/hello-world.js`.

yet, if i add the file under `/assets/hello-world.js`, then it doesn't get served via `http://mysite/assets/hello-world.js`.

i presume that is because of this nginx config:

```
server {
    listen 80;
    server_name $http_host;
    root /var/www/html;

    location /assets {
        try_files $uri =404;
    }
}
```

just not sure what the point is of having `/assets` as a volume if it isn't going to get served by nginx
