### ISSUE TITLE
Suggesting major changes

### ISSUE THREAD

**Issue by vrslev** [frappe/frappe_docker#606]
I really don't like how this repository is structured. Big part of code is not tested or documented, a lot of stuff repeats time to time. It's hard to keep up (and maintain I guess). My understanding is, frappe/frappe_docker was growing into something with "this", and "that", and "that".

I created new repository as proof that we can do better and simpler: https://github.com/vrslev/new_frappe_docker.

My proposal is to deprecate this repository (but obviously keep maintaining it for some time) and create new one (frappe/docker). I would be happy to keep sending PRs to improve current project, but too many breaking changes are required and in the end nobody would recognize the project before changes. 

 @revant I suggest to carefully look in my code. Thoughts?

**Comment by revant** [comment]
this repository is used by helm charts.

why change the names for images? can we keep things backward compatible for images?

**Comment by vrslev** [comment]
> why change the names for images?

Because they don’t actually represent what they do. Also I changed the purpose of `frappe-nginx`. 

> this was done by me once. It doesn't matter as long as images are backward compatible.

In my repo I removed majority of extra functionality. Can we do such thing here?

**Comment by revant** [comment]
if the images are better optimised we need to propogate all of it to Kubernetes helm chart.

can you try the k3d locally with your images?
I can help in making a helm chart for it.

check this script to test everything locally. https://github.com/frappe/helm/blob/main/tests/script.sh

**Comment by revant** [comment]
I'll not prefer traefik as a mandatory service.
Community not adopting docker for learning overhead, adding traefik will distance it further.
Right now anyone who tweaks `frappe-bench/config/nginx.conf` can do similar things in frappe-nginx it even has an option to completely override the config file. It makes migrating apps from native setups to containers easier. No need of additional translation from nginx to traefik.

**Comment by vrslev** [comment]
> can you try the k3d locally with your images?

Let's test it after all.

> Right now anyone who tweaks frappe-bench/config/nginx.conf can do similar things in frappe-nginx

Does [this config](https://github.com/frappe/frappe_docker/blob/main/build/frappe-nginx/nginx-default.conf.template) has to be this complicated? Also I don't like runtime config generation. With Traefik everything is quite simple and explicit. 

> No need of additional translation from nginx to traefik.

We can remove Traefik service from main compose file, configure Nginx to expose port and add Traefik only in [https override](https://github.com/vrslev/new_frappe_docker/blob/main/overrides/compose.https.yml).

> It makes migrating apps from native setups to containers easier.

When I was migrating, it wasn't easy exactly because of networking. I think we need to change something.

**Comment by revant** [comment]
> Does this config has to be this complicated? Also I don't like runtime config generation. With Traefik everything is quite simple and explicit.

it is copy of https://github.com/frappe/bench/blob/develop/bench/config/templates/nginx.conf

keeping it as close to bench as possible

I really don't mind new improved technologies. Just that the more it differs from upstream more we'll have to support without any upstream help to support issues/repo

we get help from upstream if errors are translated to native setups very quickly. 

nginx configs are part of syllabus. traefik is out of syllabus.

> We can remove Traefik service from main compose file, configure Nginx to expose port and add Traefik only in https override.

this nginx can be closer to bench I guess.

I'm open to explore new thing as long as it is propagated to helm charts and seamlessly help people migrate their current k8s setups. I can bump the helm charts by Major version and add migration path in readme if needed

**Comment by vrslev** [comment]
@revant Can we get rid of the scripts? https://github.com/vrslev/new_frappe_docker#scripts

**Comment by revant** [comment]
- remove auto migrate
- check_connection/doctor we need some liveness/readiness probe for the workers and scheduler for kubernetes, gunicorn and socketio containers can check ping to port 9k,8k, other containers don't have ports to check health. also there is no such thing as depends_on in swarm or k8s, there the container keeps restarting
- new site should work for users `@%`, also with postgres.
- push/restore: need something for daily backups https://helm.erpnext.com/kubernetes-resources/create-push-backups-to-cloud-job, suggest alternative

**Comment by revant** [comment]
Instead of `redis-cache`, `redis-queue` and `redis-socketio` container it can use just 1 redis container and use the database feature of redis. e.g. `redis:6379/0`, `redis:6379/1`, `redis:6379/2`

**Comment by vrslev** [comment]
Can you give an example or reference of this feature?

**Comment by vrslev** [comment]
> new site should work for users @%, also with postgres.

They work due to [this patch](https://github.com/vrslev/new_frappe_docker/blob/main/build/backend/patched_bench_helper.py).

> push/restore: need something for daily backups https://helm.erpnext.com/kubernetes-resources/create-push-backups-to-cloud-job, suggest alternative

OK, I will dig into that 😃

**Comment by revant** [comment]
> They work due to this patch.

does it belong to core code? we can fix upstream and then remove patch?

**Comment by vrslev** [comment]
> does it belong to core code? we can fix upstream and then remove patch?

It patches the core code. But the idea to restrict access only to current host is good, don't you think?

**Comment by revant** [comment]
> idea to restrict access only to current host is good

Something like `new-site --mariadb-no-socket` can be done for postgres? It was an attempt to override explictly.

For backup the backend can be used as environment and any python script can be mounted as file/config/configMap and executed.

Thoughts on naming. backend means webserver+worker. socketio is also backend?
Why not backend, websocket, frontend?

Somewhere I found js assets and node_modules are needed in gunicorn as well. Somewhere jinja template uses may be. I remember there was also a migration patch that the runs a nodejs script to build website theme. Just like the python2 for version-12/node-gyp superstition, you will find it after rigorous testing or on issues.

**Comment by revant** [comment]
> Can you give an example or reference of this feature?

Here is my `devcontainer/docker-compose.yml`

```yaml
version: "3.7"
services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=root
      # Sometimes db initialization takes longer than 10 seconds and site-creator goes away.
      # Frappe doesn't use CONVERT_TZ() function that requires time zone info, so we can just skip it.
      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes:
      - mariadb-vol:/var/lib/mysql

  # Enable PostgreSQL only if you use it, see development/README.md for more information.
  # postgresql:
  #   image: postgres:11.8
  #   restart: on-failure
  #   environment:
  #     - POSTGRES_PASSWORD=123
  #   volumes:
  #     - postgresql-vol:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/development
    ports:
      - "8000-8005:8000-8005"
      - "9000-9005:9000-9005"

volumes:
  mariadb-vol:
  postgresql-vol:
```

common_site_config.json:

```json
{
 "background_workers": 1,
 "file_watcher_port": 6788,
 "frappe_user": "frappe",
 "gunicorn_workers": 17,
 "live_reload": true,
 "rebase_on_pull": false,
 "redis_cache": "redis://redis:6379/0",
 "redis_queue": "redis://redis:6379/1",
 "redis_socketio": "redis://redis:6379/2",
 "db_host": "mariadb",
 "restart_supervisor_on_update": false,
 "restart_systemd_on_update": false,
 "serve_default_site": true,
 "shallow_clone": true,
 "socketio_port": 9000,
 "use_redis_auth": false,
 "webserver_port": 8000,
 "developer_mode": 1
}
```
