### ISSUE TITLE
Add a local mail handler to test email workflows

### ISSUE THREAD

**Issue by sebastian-code** [frappe/frappe_docker#744]
**Is your feature request related to a problem? Please describe.**
By default, Frappe uses its own SMTP workflow to handle emails, but on development, sometimes you found yourself in need of sending a lot of emails, which could hurt your email account reputation.

**Describe the solution you'd like**
A docker container running Mailhog, or something similar, allowing me to check safely the emails I need to create, and test for.

**Comment by revant** [comment]
devcontainer-example is meant for this.

Once you copy it to `.devcontainer` directory it will be gitignored.

Add additional services to docker-compose and use them?

**Comment by sebastian-code** [comment]
Yes, something like that. I'm far from skilled with Docker, and the point would be to include it as part of the current workflow, and into the documentation, as an official element for the Frappe Docker project.

**Comment by revant** [comment]
I've not used MailHog.

to add it to your devcontainer `services` add following to `.devcontainer/docker-compose.yml` under the `services`:


```yaml
...
  # https://github.com/mailhog/MailHog/blob/master/docs/DEPLOY.md#docker
  mailhog:
    image: mailhog/mailhog:v1.0.1
    environment:
      - MH_STORAGE=maildir
    volumes:
      - $HOME/maildir:/maildir
    ports:
      - 1025:1025
      - 8025:8025
...
```

after adding, rebuild the devcontainer.

You will be able to access mailhog as hostname `mailhog` from the frappe/bench devcontainer.
To access webui from localhost you can visit `http://localhost:8025`

If you add it and successfully use it, add this and whatever you do to make it work as part of documentation.
