### ISSUE TITLE
Assets directory remains empty and file not found errors are thrown

### ISSUE THREAD

**Issue by dirkackerman** [frappe/frappe_docker#746]
Note: I've build a docker compose file based on the compose.yml and overrides contained in this repo. My issue does however seem to stem from the compose.yml config and the images themself.

## Description of the issue
Current compose.yml has moved the assets volume path away from the location seen in online documents.

In the current mapping this leaves a clean install of the ERPNext containers with an empty assets directory and no static content (css, js etc.) can be served. 404 result codes are returned on these calls.

Moving the mapping to the previous /assets path cause the static content to be served again but backend starts to fail with not found resources in the ...sites/assets directory. The setup wizard pyhton file for ERPNext for example.

The start-up script for the ERPNext NGINX container is said to have included a rsync command to ensure the /assets directory is synced with the static content in the NGINX container. This seems to have been removed.

Performing a manual cp of the assets directory in the NGINX container to /assets does solve the problem as a manual work around.

## Context information (for bug reports)
```
frontend:
    image: frappe/frappe-nginx:${FRAPPE_VERSION}
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-$$host}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
    volumes:
      - sites:/usr/share/nginx/html/sites
      - assets:/usr/share/nginx/html/assets
```

The assets volume seems to have been mapped to /assets in the past.

## Steps to reproduce the issue

docker compose up
Navigate to login screen

### Observed result
File not found on static content

### Expected result
Login page to render successfully.
