### ISSUE TITLE
Why is the script/command restore_backup.py removed?

### ISSUE THREAD

**Issue by KevinErath** [frappe/frappe_docker#764]
I noticed that you have reorganized the internal structure of the scriptfiles (e.g. renaming install_app to install-app..), but you also removed the functioanlity to restore a backup from a S3 bucket. Is there an alternative way to automatically restore a backup from S3?

**Comment by revant** [comment]
@vrslev can explain better.

`bench restore` command exists.

mount it as a configmap, config or file and use it if needed.

**Comment by 1ubuntuuser** [comment]
@revant thank you for your responses as always. 

In my case, I would like to create a template site, then duplicate this site with every new setup. Each member in my not for profit organisation will be requiring their own site. This means I should never have to restore a large site, as they will be templates with minimal data.

Would you be able to provide a few more details or a link to more details on this statement?
> mount it as a configmap, config or file and use it if needed.

**Comment by revant** [comment]
> Would you be able to provide a few more details or a link to more details on this statement?

mounting a config like this: https://gist.github.com/revant/6a67f775aa8198f9b306f32d6872799f#file-erpnext-v13-backup-yaml-L15

or just a plain file will also do:

```yaml
version: "3.7"
services:
  restore:
    ...
    entrypoint: ["/home/frappe/frappe-bench/env/bin/python"]
    command: ["/opt/restore.py"]
    volumes:
        - /host/path/to/restore.py:/opt/restore.py
```

for kubernetes use ConfigMap:

```yaml
kind: ConfigMap
...
data:
  restore.py: |
    def main():
      print("Restore")
    ...
```
