### ISSUE TITLE
Traefik not loading certificate and nginx not serving site

### ISSUE THREAD

**Issue by jkunczik** [frappe/frappe_docker#821]
## Description of the issue
First of all thanks for the great work!

After creating a new erpnext deployment performing [the setup of ERPNext using containerized MariaDB and Redis with Letsencrypt certificates](https://github.com/frappe/frappe_docker/blob/main/docs/setup-options.md#setup-erpnext-using-containerized-mariadb-and-redis-with-letsencrypt-certificates), i got a SSL warning. After accepting it, nginx presented me with a 404 <site-name>  not found.

I compared the config files with my previous frappe v12 deployment and saw that 

`      - "traefik.http.routers.erpnext-nginx.rule=Host(${SITES})"`

was not set in the labels of nginx in the docker-compose.yml file. Instead

`      traefik.http.routers.frontend-http.rule: HostRegexp(`{any:.+}`)`

was given. In the [Treafik documentation](https://doc.traefik.io/traefik/https/acme/#domain-definition) I found that only Host() matchers or a tls.domains work to identify URLs for which to get a SSL certificate. Hence I added:

`      traefik.http.routers.frontend-http.tls.domains[0].main: "<site-name>"`

and afterwards it worked. Did I do something wrong during my setup, or did I find a bug?

## Steps to reproduce the issue

1.  I deployed a single server erpnext instance using the following script:

```
docker compose -f compose.yaml \
  -f overrides/compose.erpnext.yaml \
  -f overrides/compose.mariadb.yaml \
  -f overrides/compose.redis.yaml \
  -f overrides/compose.https.yaml \
  config > ~/gitops/docker-compose.yml
```
2. and then a new site using the bench:

`docker-compose exec backend bench new-site <site-name> --mariadb-root-password <db-password> --admin-password <admin-password>`

### Observed result
Surfing to <site-name> leads to an SSL warning. After accepting the SSL warning nginx shows a a 404 <site-name>  not found.

### Expected result
A valid TLS session and the UI of the site, I just created

**Comment by revant** [comment]
> and afterwards it worked.

We can fix the related yaml(s)/docs? Can you send the change you did as PR?

> Did I do something wrong during my setup, or did I find a bug?

I don't think it is a bug with traefik or frappe/erpnext.
I just added a label for `configuration` just in case.

**Comment by shahin-trunk** [comment]
Same issue here. No SSL warnings but 404 Not Found on requesting page @ one.domain.com, two.domain.com

**Comment by shahin-trunk** [comment]
docker ps shows

CONTAINER ID   IMAGE                             COMMAND                  CREATED          STATUS                 PORTS                                      NAMES
88b7fcd207ae   frappe/erpnext-nginx:v13.34.1     "/docker-entrypoint.…"   11 minutes ago   Up 11 minutes          8080/tcp                                   erpnext-one_frontend_1
b88ce99a9673   frappe/frappe-socketio:v13.33.1   "docker-entrypoint.s…"   11 minutes ago   Up 11 minutes                                                     erpnext-one_websocket_1
a5d3beda705d   frappe/erpnext-worker:v13.34.1    "bench worker --queu…"   11 minutes ago   Up 11 minutes                                                     erpnext-one_queue-short_1
e230a7fe49df   frappe/erpnext-worker:v13.34.1    "bench schedule"         11 minutes ago   Up 11 minutes                                                     erpnext-one_scheduler_1
385840c55024   frappe/erpnext-worker:v13.34.1    "/home/frappe/frappe…"   11 minutes ago   Up 11 minutes                                                     erpnext-one_backend_1
814a38922a46   frappe/erpnext-worker:v13.34.1    "bench worker --queu…"   11 minutes ago   Up 11 minutes                                                     erpnext-one_queue-default_1
3dbfeadefbb4   frappe/erpnext-worker:v13.34.1    "bench worker --queu…"   11 minutes ago   Up 11 minutes                                                     erpnext-one_queue-long_1
f1980e1ad22f   redis:6.2-alpine                  "docker-entrypoint.s…"   11 minutes ago   Up 11 minutes          6379/tcp                                   erpnext-one_redis_1
5b56276acbb0   traefik:v2.6                      "/entrypoint.sh --pr…"   22 minutes ago   Up 22 minutes          0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   traefik_traefik_1
8ae7ad348c4a   mariadb:10.6                      "docker-entrypoint.s…"   2 hours ago      Up 3 hours (healthy)   3306/tcp                                   mariadb-database

**Comment by jkunczik** [comment]
> We can fix the related yaml(s)/docs? Can you send the change you did as PR?

Sure! Although I don't completely understand the switch from:  `"traefik.http.routers.erpnext-nginx.rule=Host(${SITES})"` to: `traefik.http.routers.frontend-http.rule: HostRegexp({any:.+})`

I have the feeling somebody wanted to get rid of the _SITES_ variable to make the deployment more dynamic. Explicetly adding domains to the docker-compose again - like I did for my workaround - yields the exact opposite. 

@revant Is there something in the new docker stack (like a shell script) that is supposed to add the domain to nginx?

**Comment by jkunczik** [comment]
@shahin-trunk If you don't see a SSL error, I suppose the problem is slightly different, as nginx seems to get a valid SSL certificate (or does not enforce SSL). 

Have you tried adding  both domains to the labels of your frontend container in the docker-compose.yaml, like so:

  ```
frontend:
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: erptest.docsinclouds.com
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: frappe/erpnext-nginx:v13.33.0
    labels:
      traefik.enable: "true"
      traefik.http.routers.frontend-http.entrypoints: websecure
      traefik.http.routers.frontend-http.rule: HostRegexp(`{any:.+}`)
      traefik.http.routers.frontend-http.tls.certresolver: main-resolver
      traefik.http.routers.frontend-http.tls.domains[0].main: "one.domain.com"
      traefik.http.routers.frontend-http.tls.domains[1].main: "two.domain.com"
      traefik.http.services.frontend.loadbalancer.server.port: "8080"
```
