### ISSUE TITLE
Docker Swarm Upgrade v13.21.1 to v13.22.2

### ISSUE THREAD

**Issue by miguelurtado** [frappe/frappe_docker#829]
Hello peoples...!

I installed ERPNext in Docker Swarm using this tutorial - https://github.com/frappe/frappe_docker/blob/compat/docs/docker-swarm.md

Even after updating ENVs, seted folder/volume assets and sites to uid:gid 1000:1000 this not work:

New ENVs in yml file.
```
  erpnext-nginx:
    environment:
      - BACKEND=erpnext-python:8000
      - SOCKETIO=frappe-socketio:9000
      - FRAPPE_SITE_NAME_HEADER=${FRAPPE_SITE_NAME_HEADER:-$host}
      - UPSTREAM_REAL_IP_ADDRESS=${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      - UPSTREAM_REAL_IP_HEADER=${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      - UPSTREAM_REAL_IP_RECURSIVE=${UPSTREAM_REAL_IP_RECURSIVE:-off}
     volumes:
      - sites-vol:/usr/share/nginx/html/sites
      - assets-vol:/usr/share/nginx/html/assets
      #- sites-vol:/var/www/html/sites
      #- assets-vol:/assets
```
 

Error on open erp.exemple.com/app/communication/XXXXXXXX
```FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/node_modules/ace-builds/src-min-noconflict/ace.js'```

Error on save custom site theme:
```
Error: Cannot find module 'node-sass'
Require stack:
- /home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._load (internal/modules/cjs/loader.js:746:27)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:101:18)
at Object. (/home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js:1:14)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js'
]
}
```

Thanks frappe...!

_Originally posted by @miguelurtado in https://github.com/frappe/frappe_docker/issues/719#issuecomment-1164762763_
