### ISSUE TITLE
[Custom app] problem with persistent volumes

### ISSUE THREAD

**Issue by sdfateh** [frappe/frappe_docker#872]
## Description of the issue
The Problem happened when a new custom app or new assets files was added to the image, it caused 2 issues:

1- `The Assets`: when you first initialize the compose file, it creates assets and sites volumes, and as Docker's logic is, these volumes are untouchable from the outside and preserve their contents, SO if any new directory (which is new app) does not appear in the volume which means that the data of the public directory does not exist for a new app or if there is new data for existing apps ( Frappe & Erpnext included)

2- `apps.txt`: when a new custom app was added to the image new line with a new app name is written in the apps.txt file, but for the same problem as before because the volume is persistent new apps.txt can't appear in the volume

### Suggestions:

1- Is assets volume have to be persistent? what if we put its data in both the backend and frontend to prevent making it persistent?

2- for `apps.txt` the problem is much lighter because it's easy to add it manually, but I don't have an idea if it's a way to make this file only as non-persistent

### Note:
If I delete the volumes all data comes true because the image is built well and has all data, the problem is just from volumes.

**Comment by revant** [comment]
I run a container once that does this:

```yaml
  populate-assets:
    image: frappe/erpnext-nginx:${VERSION}
    deploy:
      restart_policy:
        condition: none
    entrypoint: ["sh", "-c"]
    command:
      - >
        cp -fR /usr/share/nginx/html/assets /data;
        touch /data/sites/.build;
    volumes:
      - assets-vol:/data/assets:rw
      - sites-vol:/data/sites:rw
```

For Kubernetes deployment I'm doing this in initContainers.

```
      initContainers:
        - name: populate-assets
          {{- if .Values.worker.gunicorn.envVars }}
          env:
            {{- toYaml .Values.worker.gunicorn.envVars | nindent 12 }}
          {{- end }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          command:
            - cp
            - -fR
          args:
            - /usr/share/nginx/html/assets
            - /home/frappe/frappe-bench/sites
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: assets-cache
              mountPath: /home/frappe/frappe-bench/sites/assets
```
