### ISSUE TITLE
Add Mailhog container to local dev setup to test E-Mail Sending

### ISSUE THREAD

**Issue by WebsiteDeveloper** [frappe/frappe_docker#904]
For Local Development it would be nice to have a Mailhog setup

https://github.com/mailhog/MailHog
https://hub.docker.com/r/mailhog/mailhog/

To Enable local Testing of E-Mails Sent by ERPNext and Frappe

**Comment by revant** [comment]
This is alternative docker-compose.yml that has minio for s3 and mailhog. I uses bitnami/mariadb instead of mariadb (you can skip that part).

```yaml
version: "3.7"

services:
  mariadb:
    image: bitnami/mariadb:10.6
    restart: unless-stopped
    environment:
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE: utf8mb4_unicode_ci
      MARIADB_ROOT_PASSWORD: 123
      MARIADB_EXTRA_FLAGS: --skip-character-set-client-handshake --skip-innodb-read-only-compressed
    volumes:
      - ${HOME}/data/mariadb:/bitnami/mariadb
      # - mariadb-data:/bitnami/mariadb

  fix-mariadb-permissions:
    image: bitnami/mariadb:10.6
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
      - ${HOME}/data/mariadb:/bitnami
      # - mariadb-data:/bitnami

  mailhog:
    image: mailhog/mailhog:v1.0.1
    environment:
      - MH_STORAGE=maildir
    volumes:
      - ${HOME}/data/mailhog:/maildir
      # - mailhog-data:/maildir
    ports:
      - 1025:1025
      - 8025:8025

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - ${HOME}/data/minio:/data
      # - minio-data/data/minio:/data
    command:
      - server
      - --console-address=:10000
      - /data
    ports:
      - 10000:10000

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  redis-socketio:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      - ..:/workspace:cached
      - ${HOME}/.ssh:/home/frappe/.ssh
    working_dir: /workspace/development
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005


# volumes:
#   mariadb-data:
#   minio-data:
#   mailhog-data:

```
