### ISSUE TITLE
Error: Cannot find module 'chalk'

### ISSUE THREAD

**Issue by smmitc** [frappe/frappe_docker#908]
## Description of the issue
With ERPNext v14 I'm not able to create a new Website Theme. I've tested Versions up to 14.0.3.

## Context information (for bug reports)
Installation of the test environment:
```
git clone https://github.com/frappe/frappe_docker
cd frappe_docker
cp example.env .env
mkdir ~/gitops
docker compose -f compose.yaml \
  -f overrides/compose.noproxy.yaml \
  -f overrides/compose.erpnext.yaml \
  -f overrides/compose.mariadb.yaml \
  -f overrides/compose.redis.yaml \
  config > ~/gitops/docker-compose.yml

docker compose --project-name example -f ~/gitops/docker-compose.yml up -d
docker exec example-backend-1 bench new-site localhost --mariadb-root-password 123 --admin-password secret --install-app erpnext
```

## Steps to reproduce the issue

1. Go to [Website](http://localhost:8080/app/website)
2. Click [Website Theme](http://localhost:8080/app/website-theme)
3. Click [Add Website Theme](http://localhost:8080/app/website-theme/new-website-theme-2)
4. Enter a name, e.g. 'Test'
5. Click Save

### Observed result
![Cannot find module chalk](https://user-images.githubusercontent.com/110170775/187860511-611f3c19-614c-46a7-816a-45346676825c.png)

### Expected result
New Website Theme without errors.

### Stacktrace / full error message if available

```
Error: Cannot find module 'chalk'
Require stack:
- /home/frappe/frappe-bench/apps/frappe/esbuild/utils.js
- /home/frappe/frappe-bench/apps/frappe/esbuild/sass_options.js
- /home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._load (internal/modules/cjs/loader.js:746:27)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:101:18)
at Object. (/home/frappe/frappe-bench/apps/frappe/esbuild/utils.js:3:15)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/home/frappe/frappe-bench/apps/frappe/esbuild/utils.js',
'/home/frappe/frappe-bench/apps/frappe/esbuild/sass_options.js',
'/home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js'
]
}
```

Someone solved this issue in [this post](https://discuss.erpnext.com/t/error-cannot-find-module-chalk/44851) by doing
```
Step 1: bench setup socketio
Step 2: bench setup requirements
```
However as far as I know this has to be done when creating the image.

**Comment by smmitc** [comment]
I have the same problem with my kubernetes setup using the [official chart](https://artifacthub.io/packages/helm/erpnext/erpnext). Then I've tested the setup using docker with the same results. The initContainer of gunicorn is:
```
  initContainers:
  - args:
    - /usr/share/nginx/html/assets
    - /home/frappe/frappe-bench/sites
    command:
    - cp
    - -fR
    image: frappe/erpnext-nginx:v14.0.3
    imagePullPolicy: IfNotPresent
    name: populate-assets
    resources: {}
    securityContext:
      capabilities:
        add:
        - CAP_CHOWN
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/frappe/frappe-bench/sites/assets
      name: assets-cache
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jvmdx
      readOnly: true
```

I tried the [suggested commands](https://gist.github.com/revant/6a67f775aa8198f9b306f32d6872799f#file-erpnext-v13-yaml-L177-L189) in docker. There is no /data directory:
```
docker exec -it example-frontend-1 /bin/sh
/ $ ls
bin                   docker-entrypoint.sh  lib                   opt                   run                   sys                   var
dev                   etc                   media                 proc                  sbin                  tmp
docker-entrypoint.d   home                  mnt                   root                  srv                   usr
```

The sites volume is mounted to `/usr/share/nginx/html/sites` and it contains a directory named `assets`. So the correct command is `cp -fR /usr/share/nginx/html/assets /usr/share/nginx/html/sites`, right? But then I get the error
```
cp: can't create '/usr/share/nginx/html/sites/assets/assets.json': Permission denied
cp: can't create '/usr/share/nginx/html/sites/assets/assets-rtl.json': Permission denied
cp: can't create directory '/usr/share/nginx/html/sites/assets/erpnext': Permission denied
cp: can't create directory '/usr/share/nginx/html/sites/assets/frappe': Permission denied
cp: can't create directory '/usr/share/nginx/html/sites/assets/payments': Permission denied
```
