### ISSUE TITLE
Function not works when multi-bench

### ISSUE THREAD

**Issue by sdfateh** [frappe/frappe_docker#912]
## Description of the issue
When I use a multi-bench setup, I can't execute on this page ( on any Method not just this one) , it throws a massage that is started but nothing happens ( no logs also)

Any advice?

## Context information (for bug reports)

![image](https://user-images.githubusercontent.com/83924106/188305017-20ff4412-90b6-40c6-b826-1d1326cfe2bb.png)

**Comment by revant** [comment]
Is it a problem with containerized setup? 
Is it a problem with production setup or development setup?

If it is related to frappe or bench, I'll transfer the issue to frappe or bench

**Comment by sdfateh** [comment]
@revant 

Yes, unfortunately, it is a problem that only occurs in the case of the multi-bench container setup

**Comment by revant** [comment]
It doesn't occur with non containerized multi-bench setup?

**Comment by sdfateh** [comment]
@revant 
Yes, when a single containerized bench works fine.
in addition, I tried many experiments to try to solve the problem, the only case that worked that when I deploy multi-bench in the same server but with a database special for each compose, no `shared-mariadb`. But I think this is a bit wrong and it causes a lot of load on the server.

it's not `erpnext.stock.reorder_item.reorder_item` issue , it happened for any `scheduled-job-type` entry.

**Comment by revant** [comment]
can you share more details about your stacks?

is common or external redis is used?

**Comment by ankush** [comment]
Also can you share what's queue name being used on RQ workers in different benches? 


![telegram-cloud-photo-size-5-6131985999354511154-y](https://user-images.githubusercontent.com/9079960/190407391-23eba467-ef80-4116-a979-4607b4dfc9f1.jpg)

**Comment by sdfateh** [comment]
DB stack :
```
version: "3.3"

services:
  database:
    container_name: mdb-database
    image: mariadb:10.6
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h localhost --password=${DB_PASSWORD:-changeit}
      interval: 1s
      retries: 15
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --max-allowed-packet=3G
      - --innodb_buffer_pool_size=4G
      - --innodb-log-file-size=512M
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-changeit}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dep

networks:
  dep:
    name: dep
    external: false

volumes:
  db-data:
```

App stack :

```
x-depends-on-configurator: &depends_on_configurator
  depends_on:
    configurator:
      condition: service_completed_successfully        
  networks:
     - bench-network 

x-backend-defaults: &backend_defaults
  <<: *depends_on_configurator
  image: IMAGE_NAME
  volumes:
    - sites:/home/frappe/frappe-bench/sites
  networks:
     - bench-network
     - dep
  
services:
  configurator:
    image: IMAGE_NAME
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    networks:
       - bench-network
    command: configure.py
    environment:
      DB_HOST: database
      DB_PORT: 3306
      REDIS_CACHE: redis:6379/0
      REDIS_QUEUE: redis:6379/1
      REDIS_SOCKETIO: redis:6379/2
      SOCKETIO_PORT: 9000   
    
  backend:
    <<: *backend_defaults
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - assets:/home/frappe/frappe-bench/sites/assets:ro

  populate-assets:
    image: IMAGE_NAME
    entrypoint: ["sh", "-c"]
    command:
      - >
        cp -fR /usr/share/nginx/html/assets /data;
    volumes:
      - assets:/data/assets:rw

  frontend:
    image: IMAGE_NAME
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: $$host
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.${SOME_NAME}-secure.entrypoints=websecure
      - traefik.http.routers.${SOME_NAME}.rule=HostRegexp(`${SOME_NAME}.company.com`)
      - traefik.http.routers.${SOME_NAME}-secure.service=${SOME_NAME}
      - traefik.http.services.${SOME_NAME}.loadbalancer.server.port=8080 

    networks:
      - proxy
      - bench-network

    volumes:
      - sites:/usr/share/nginx/html/sites
      - assets:/usr/share/nginx/html/assets
    depends_on:
      - backend
      - websocket
      - populate-assets

  websocket:
    <<: *depends_on_configurator
    image: frappe/frappe-socketio:v13
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  queue-short:
    <<: *backend_defaults
    command: bench worker --queue short

  queue-default:
    <<: *backend_defaults
    command: bench worker --queue default

  queue-long:
    <<: *backend_defaults
    command: bench worker --queue long

  scheduler:
    <<: *backend_defaults
    command: bench schedule

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data
    networks:
      - dep
      - bench-network
volumes:
  sites:
  assets:
  redis-data:

networks:
  proxy:
    external: true  
  dep:
    external: true  
  bench-network:
    name: SOME_NAME
```

@revant Any advice ?
