### ISSUE TITLE
Assets from custom apps dont get copied properly 

### ISSUE THREAD

**Issue by DrZoidberg09** [frappe/frappe_docker#919]
Hi there,

I am trying to build by own docker image including my custom apps. However, I have issues that the assets are missing.

Basically, the assets folder in the nginx image just contains the base folders: Frappe, ERPNExt and Payment. 

The asset folder in the worker image just contains folders for erpnext and one of the custom apps, but the folders are empty.

Any clue what the problem is? Could it be the cleanup function of the install-app.sh ?

This is the dockerfile for the nginx image:

> ARG FRAPPE_VERSION
ARG ERPNEXT_VERSION
FROM frappe/assets-builder:${FRAPPE_VERSION} as assets
ARG APP_NAME1
COPY . apps/${APP_NAME1}
RUN install-app ${APP_NAME1}
ARG APP_NAME2
COPY . apps/${APP_NAME2}
RUN install-app ${APP_NAME2}
ARG APP_NAME3
COPY . apps/${APP_NAME3}
RUN install-app ${APP_NAME3}
ARG APP_NAME4
COPY . apps/${APP_NAME4}
RUN install-app ${APP_NAME4}
ARG APP_NAME5
COPY . apps/${APP_NAME5}
RUN install-app ${APP_NAME5}
ARG APP_NAME6
COPY . apps/${APP_NAME6}
RUN install-app ${APP_NAME6}
ARG APP_NAME7
COPY . apps/${APP_NAME7}
RUN install-app ${APP_NAME7}
FROM frappe/erpnext-nginx:${ERPNEXT_VERSION}
COPY --from=assets /out /usr/share/nginx/html

**Comment by sdfateh** [comment]
Add this to the end of your frontend Dockerfile :
```
# The next layers are for [populate-assets]
USER root
RUN chown -R 1000:root /usr/share/nginx/html/assets 
USER 1000
```

and in your compose add this service :
```
  populate-assets:
    image: frappe/erpnext-nginx:${FRAPPE_VERSION}
    entrypoint: ["sh", "-c"]
    command:
      - >
        cp -fR /usr/share/nginx/html/assets /data;
    volumes:
      - assets:/data/assets:rw
```

**Comment by DrZoidberg09** [comment]
Thank you! 

I will use the docker container in Kubernetes. Is there an equivalent version for the compose?

**Comment by sdfateh** [comment]
As @revant guide me once,
In Kubernetes you can use this:

```
  populate-assets:
    image: frappe/erpnext-nginx:${VERSION}
    deploy:
      restart_policy:
        condition: none
    entrypoint: ["sh", "-c"]
    command:
      - >
        cp -fR /usr/share/nginx/html/assets /data;
        touch /data/sites/.build;
    volumes:
      - assets-vol:/data/assets:rw
      - sites-vol:/data/sites:rw
For Kubernetes deployment I'm doing this in initContainers.

      initContainers:
        - name: populate-assets
          {{- if .Values.worker.gunicorn.envVars }}
          env:
            {{- toYaml .Values.worker.gunicorn.envVars | nindent 12 }}
          {{- end }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          command:
            - cp
            - -fR
          args:
            - /usr/share/nginx/html/assets
            - /home/frappe/frappe-bench/sites
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: assets-cache
              mountPath: /home/frappe/frappe-bench/sites/assets
```
