### ISSUE TITLE
Custom app name was not added in /sites/assets

### ISSUE THREAD

**Issue by fecoderchinh** [frappe/frappe_docker#931]
Hello Frappe Team,
I have installed production mode for frappe docker successfully.
But my custom images were not loaded on the webite and when i inspected into `/sites/assets` directory i did not see my custom app name there.

![image](https://user-images.githubusercontent.com/13318452/190972214-724294e3-4857-47f6-987d-24882cfc94c4.png)

I think this is the reason that i could not load the image.

Could you please help me to check and advise for this?

i was trying to custom `myapp` via @revant repo [castlecraft](https://github.com/castlecraft/custom_frappe_docker)

Regards.

**Comment by revant** [comment]
can you try to populate assets and check if it works?

https://github.com/frappe/frappe_docker/issues/872#issuecomment-1203708755

**Comment by fecoderchinh** [comment]
Hi @revant 
I tried touch but get another error msg
`touch: cannot touch '/home/frappe/frappe-bench/sites/assets/myapp': Read-only file system`
Here is my docker
```
backend:
    build:
      context: .
      dockerfile:  ./images/backend.Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    entrypoint: [ "sh", "-c" ]
    command:
      - >
        touch /home/frappe/frappe-bench/sites/assets/myapp;
```
