### ISSUE TITLE
Cannot mount assets volume

### ISSUE THREAD

**Issue by fecoderchinh** [frappe/frappe_docker#938]
Hello everyone,
I tried to mount the frappe volume to my local but it did not work.
The assets directory is empty.

I have consider to read the related issues but it did not solve my problem.
Could you please help me to check and advise on this?

My compose
```
assets:
    image: frappe/erpnext-worker:v14.1.2
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./sites/data:/home/frappe/frappe-bench/sites:rw
```
The container assets
![image](https://user-images.githubusercontent.com/13318452/192196991-00e647b7-eb0c-485c-993c-a435cc8340cb.png)

But the local directory is empty.
![image](https://user-images.githubusercontent.com/13318452/192197067-6e521870-442c-45cb-b555-07a805b576d0.png)
